import {
  Activity,
  Calculator,
  Calendar,
  DollarSign,
  Flame,
  Gauge,
  Percent,
  Receipt,
  Ruler,
  TrendingUp,
} from 'lucide-react'

import type { ToolMeta } from '../types'

/**
 * Calculator Tools Registry
 * ══════════════════════════════════════════════════════════════════════════
 * All calculators run in the browser. No backend required.
 * These provide genuine utility value and attract long-tail SEO traffic.
 * ══════════════════════════════════════════════════════════════════════════
 */

export const calculatorTools: ToolMeta[] = [
  {
    id: 'percentage-calculator',
    slug: 'percentage-calculator',
    title: 'Percentage Calculator',
    shortTitle: 'Percentage Calculator',
    description:
      'Calculate percentages, percentage change, percentage of a number, and more. Solve common percentage problems instantly with step-by-step explanations.',
    shortDescription: 'Calculate percentages and percentage changes.',
    category: 'calculator',
    subcategory: 'math',
    icon: Percent,
    keywords: [
      'percentage calculator',
      'calculate percentage',
      'percent calculator',
      'percentage change calculator',
      'percentage of number',
      'increase decrease percentage',
    ],
    tags: ['percentage', 'percent', 'calculator', 'math'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    seo: {
      title: 'Percentage Calculator — Calculate Percentages Online Free',
      description:
        'Calculate percentages online. Find what percent one number is of another, percentage change, and percentage increase or decrease. Free, instant.',
      keywords: [
        'percentage calculator online free',
        'calculate percentage online',
        'percentage change calculator',
        'percent of number calculator',
      ],
    },
    relatedToolSlugs: ['bmi-calculator', 'loan-calculator', 'tip-calculator', 'age-calculator'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'age-calculator',
    slug: 'age-calculator',
    title: 'Age Calculator',
    shortTitle: 'Age Calculator',
    description:
      'Calculate exact age in years, months, days, hours, minutes, and seconds. Find the age difference between two dates. Get upcoming birthday countdown.',
    shortDescription: 'Calculate exact age from birthdate to today.',
    category: 'calculator',
    subcategory: 'date',
    icon: Calendar,
    keywords: [
      'age calculator',
      'calculate age',
      'age from birthdate',
      'birthday calculator',
      'age difference calculator',
      'how old am i',
    ],
    tags: ['age', 'birthday', 'date', 'calculator'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    seo: {
      title: 'Age Calculator — Calculate Exact Age Online Free',
      description:
        'Calculate exact age in years, months, and days from birthdate. Find age differences between two dates. Birthday countdown. Free, instant.',
      keywords: [
        'age calculator online free',
        'calculate age from birthday',
        'how old am i calculator',
        'birthday age calculator',
      ],
    },
    relatedToolSlugs: ['percentage-calculator', 'bmi-calculator', 'tip-calculator', 'loan-calculator'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'bmi-calculator',
    slug: 'bmi-calculator',
    title: 'BMI Calculator',
    shortTitle: 'BMI Calculator',
    description:
      'Calculate Body Mass Index (BMI) using metric or imperial units. View your BMI category (underweight, normal, overweight, obese) with health insights.',
    shortDescription: 'Calculate BMI in metric or imperial units.',
    category: 'calculator',
    subcategory: 'health',
    icon: Activity,
    keywords: [
      'bmi calculator',
      'body mass index calculator',
      'calculate bmi',
      'bmi checker',
      'weight height calculator',
      'bmi metric imperial',
    ],
    tags: ['bmi', 'health', 'weight', 'calculator'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'BMI Calculator — Calculate Body Mass Index Free Online',
      description:
        'Calculate your BMI online with metric or imperial units. Find out if you are underweight, normal weight, overweight, or obese. Free, instant.',
      keywords: [
        'bmi calculator online free',
        'body mass index calculator',
        'calculate bmi metric',
        'bmi checker tool',
      ],
    },
    relatedToolSlugs: ['age-calculator', 'percentage-calculator', 'tip-calculator', 'loan-calculator'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'loan-calculator',
    slug: 'loan-calculator',
    title: 'Loan EMI Calculator',
    shortTitle: 'Loan Calculator',
    description:
      'Calculate monthly EMI, total interest, and total payment for any loan. Supports home loans, car loans, personal loans, and student loans with amortization schedules.',
    shortDescription: 'Calculate loan EMI, interest, and amortization schedule.',
    category: 'calculator',
    subcategory: 'finance',
    icon: DollarSign,
    keywords: [
      'loan calculator',
      'emi calculator',
      'loan emi calculator',
      'mortgage calculator',
      'loan repayment calculator',
      'interest calculator',
      'amortization calculator',
    ],
    tags: ['loan', 'emi', 'mortgage', 'finance', 'calculator'],
    difficulty: 'intermediate',
    status: 'active',
    processingMode: 'browser',
    isFeatured: true,
    seo: {
      title: 'Loan EMI Calculator — Calculate Loan Payments Online Free',
      description:
        'Calculate monthly loan EMI, total interest, and amortization schedule. Supports home, car, and personal loans. Free, instant, no sign-up.',
      keywords: [
        'loan emi calculator free',
        'mortgage calculator online',
        'loan repayment calculator',
        'emi calculator for home loan',
        'amortization schedule calculator',
      ],
    },
    relatedToolSlugs: ['percentage-calculator', 'tip-calculator', 'age-calculator', 'bmi-calculator'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'tip-calculator',
    slug: 'tip-calculator',
    title: 'Tip Calculator',
    shortTitle: 'Tip Calculator',
    description:
      'Calculate tip amount and total bill. Split the bill between any number of people. Choose custom tip percentages or enter a fixed amount.',
    shortDescription: 'Calculate tip and split bills between people.',
    category: 'calculator',
    subcategory: 'finance',
    icon: Receipt,
    keywords: [
      'tip calculator',
      'bill tip calculator',
      'split bill calculator',
      'restaurant tip calculator',
      'calculate tip percentage',
    ],
    tags: ['tip', 'bill', 'split', 'restaurant', 'calculator'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Tip Calculator — Calculate Tip & Split Bill Free Online',
      description:
        'Calculate tip amount and split the bill between people. Choose tip percentage or custom amount. Free, instant restaurant tip calculator.',
      keywords: [
        'tip calculator online free',
        'bill tip calculator',
        'split bill calculator',
        'how much tip to leave',
      ],
    },
    relatedToolSlugs: ['percentage-calculator', 'loan-calculator', 'age-calculator', 'bmi-calculator'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'gst-calculator',
    slug: 'gst-calculator',
    title: 'GST Calculator',
    shortTitle: 'GST Calculator',
    description:
      'Calculate GST (Goods and Services Tax) quickly. Add or remove GST from any amount. Supports multiple GST rates and shows the base amount, GST, and total.',
    shortDescription: 'Add or remove GST from any amount instantly.',
    category: 'calculator',
    subcategory: 'finance',
    icon: Calculator,
    keywords: [
      'gst calculator',
      'calculate gst',
      'gst inclusive calculator',
      'gst exclusive calculator',
      'goods services tax calculator',
      'vat calculator',
    ],
    tags: ['gst', 'vat', 'tax', 'finance', 'calculator'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'GST Calculator — Calculate GST Online Free',
      description:
        'Calculate GST amount online. Add or remove GST from any price. Supports all GST rates. See base price, GST amount, and total. Free, instant.',
      keywords: [
        'gst calculator online free',
        'calculate gst online',
        'gst inclusive exclusive calculator',
        'goods services tax calculator',
      ],
    },
    relatedToolSlugs: ['percentage-calculator', 'tip-calculator', 'loan-calculator', 'bmi-calculator'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  /* ── Sprint 7: New Calculator Tools ──────────────────────────────────── */
  {
    id: 'discount-calculator',
    slug: 'discount-calculator',
    title: 'Discount Calculator',
    shortTitle: 'Discount Calc',
    description:
      'Calculate discounted prices instantly. Enter the original price and discount percentage to find the final price, savings amount, and effective saving rate.',
    shortDescription: 'Calculate final price after applying a discount percentage.',
    category: 'calculator',
    subcategory: 'finance',
    icon: DollarSign,
    keywords: ['discount calculator', 'sale price calculator', 'percentage discount', 'price after discount', 'calculate savings', 'discount percentage calculator'],
    tags: ['discount', 'price', 'savings', 'calculator', 'percent'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    seo: {
      title: 'Discount Calculator — Calculate Sale Price & Savings Online Free',
      description: 'Calculate discounted price and savings online. Enter original price and discount % to get final price. Free, instant.',
      keywords: ['discount calculator online free', 'sale price calculator', 'percentage discount calculator', 'calculate savings online'],
    },
    relatedToolSlugs: ['percentage-calculator', 'gst-calculator', 'tip-calculator', 'emi-calculator'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'unit-converter',
    slug: 'unit-converter',
    title: 'Unit Converter',
    shortTitle: 'Unit Converter',
    description:
      'Convert between units of length, weight, temperature, volume, area, and speed. Covers metric and imperial units. Instant results with multiple unit outputs.',
    shortDescription: 'Convert length, weight, temperature, volume, area, and speed units.',
    category: 'calculator',
    subcategory: 'conversion',
    icon: Ruler,
    keywords: ['unit converter', 'length converter', 'weight converter', 'temperature converter', 'metric converter', 'unit conversion calculator'],
    tags: ['unit', 'converter', 'length', 'weight', 'temperature', 'metric'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    seo: {
      title: 'Unit Converter — Convert Length, Weight, Temperature Online Free',
      description: 'Convert units online: length, weight, temperature, volume, area, speed. Metric and imperial. Free, instant, no sign-up.',
      keywords: ['unit converter online free', 'length converter', 'metric to imperial converter', 'temperature unit converter'],
    },
    relatedToolSlugs: ['speed-calculator', 'bmi-calculator', 'percentage-calculator', 'discount-calculator'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'date-calculator',
    slug: 'date-calculator',
    title: 'Date Calculator',
    shortTitle: 'Date Calculator',
    description:
      'Calculate the difference between two dates in days, weeks, months, and years. Or add and subtract days, months, and years from any date to find a future or past date.',
    shortDescription: 'Calculate date differences or add/subtract time from dates.',
    category: 'calculator',
    subcategory: 'date',
    icon: Calendar,
    keywords: ['date calculator', 'date difference calculator', 'days between dates', 'add days to date', 'date math calculator'],
    tags: ['date', 'calendar', 'days', 'difference', 'calculator'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Date Calculator — Calculate Days Between Dates Online Free',
      description: 'Calculate the difference between two dates or add/subtract time from a date. Free, instant, no sign-up.',
      keywords: ['date calculator online free', 'days between dates calculator', 'date difference tool', 'add days to date calculator'],
    },
    relatedToolSlugs: ['age-calculator', 'timestamp-converter', 'calorie-calculator', 'percentage-calculator'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'compound-interest-calculator',
    slug: 'compound-interest-calculator',
    title: 'Compound Interest Calculator',
    shortTitle: 'Compound Interest',
    description:
      'Calculate compound interest with different compounding frequencies (annually, quarterly, monthly, daily). See total interest earned, final amount, and effective annual rate.',
    shortDescription: 'Calculate compound interest and final investment value.',
    category: 'calculator',
    subcategory: 'finance',
    icon: TrendingUp,
    keywords: ['compound interest calculator', 'compound interest formula', 'investment calculator', 'interest calculator', 'compound growth calculator'],
    tags: ['compound interest', 'investment', 'finance', 'calculator', 'interest'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Compound Interest Calculator — Calculate Investment Growth Free',
      description: 'Calculate compound interest online. See total interest and final amount with different compounding frequencies. Free, instant.',
      keywords: ['compound interest calculator online free', 'compound interest formula calculator', 'investment growth calculator', 'compound growth calculator'],
    },
    relatedToolSlugs: ['loan-calculator', 'emi-calculator', 'percentage-calculator', 'discount-calculator'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'calorie-calculator',
    slug: 'calorie-calculator',
    title: 'Calorie Calculator',
    shortTitle: 'Calorie Calculator',
    description:
      'Calculate your daily calorie needs using the Mifflin-St Jeor equation. Get BMR (Basal Metabolic Rate), TDEE (Total Daily Energy Expenditure), and targets for weight loss or gain.',
    shortDescription: 'Calculate BMR and daily calorie needs for your activity level.',
    category: 'calculator',
    subcategory: 'health',
    icon: Flame,
    keywords: ['calorie calculator', 'bmr calculator', 'tdee calculator', 'daily calorie needs', 'calorie counter', 'weight loss calorie calculator'],
    tags: ['calories', 'bmr', 'tdee', 'health', 'fitness', 'calculator'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Calorie Calculator — Calculate BMR & TDEE Online Free',
      description: 'Calculate your daily calorie needs using BMR and activity level. Get weight loss and gain targets. Free, instant.',
      keywords: ['calorie calculator online free', 'bmr calculator', 'tdee calculator online', 'daily calories calculator'],
    },
    relatedToolSlugs: ['bmi-calculator', 'age-calculator', 'percentage-calculator', 'unit-converter'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'emi-calculator',
    slug: 'emi-calculator',
    title: 'EMI Calculator',
    shortTitle: 'EMI Calculator',
    description:
      'Calculate Equated Monthly Installment (EMI) for loans. Enter principal, interest rate, and tenure to get monthly EMI, total payable amount, and total interest.',
    shortDescription: 'Calculate loan EMI, total interest, and total payable amount.',
    category: 'calculator',
    subcategory: 'finance',
    icon: Receipt,
    keywords: ['emi calculator', 'loan emi calculator', 'equated monthly installment', 'home loan emi', 'car loan emi', 'personal loan emi'],
    tags: ['emi', 'loan', 'finance', 'calculator', 'interest'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    seo: {
      title: 'EMI Calculator — Calculate Loan EMI Online Free',
      description: 'Calculate loan EMI online. Get monthly installment, total interest, and total payable amount. Home, car, personal loans. Free, instant.',
      keywords: ['emi calculator online free', 'loan emi calculator', 'home loan emi calculator', 'car loan emi calculator india'],
    },
    relatedToolSlugs: ['loan-calculator', 'compound-interest-calculator', 'percentage-calculator', 'discount-calculator'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'speed-calculator',
    slug: 'speed-calculator',
    title: 'Speed, Distance & Time Calculator',
    shortTitle: 'Speed Calculator',
    description:
      'Calculate speed, distance, or time using the fundamental formula. Enter any two values to calculate the third. Supports km/h, mph, m/s with metric and imperial units.',
    shortDescription: 'Calculate speed, distance, or time — enter any two to find the third.',
    category: 'calculator',
    subcategory: 'physics',
    icon: Gauge,
    keywords: ['speed calculator', 'distance time speed calculator', 'speed distance time formula', 'velocity calculator', 'mph to kmh', 'average speed calculator'],
    tags: ['speed', 'distance', 'time', 'calculator', 'physics'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Speed Calculator — Calculate Speed, Distance & Time Free',
      description: 'Calculate speed, distance, or time online. Enter any two values to find the third. Supports km/h, mph, m/s. Free, instant.',
      keywords: ['speed calculator online free', 'distance time calculator', 'speed distance time formula calculator', 'average speed calculator'],
    },
    relatedToolSlugs: ['unit-converter', 'percentage-calculator', 'date-calculator', 'bmi-calculator'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
]


