import {
  ArrowLeftRight,
  Binary,
  Barcode,
  Braces,
  CheckCircle2,
  Clock,
  Code,
  Contrast,
  Eye,
  FileCode,
  FileSpreadsheet,
  FileText,
  Fingerprint,
  GitCompare,
  Hash,
  Key,
  Link,
  Minimize2,
  Network,
  Palette,
  Search,
  Shield,
  Table,
  Wand2,
  Workflow,
} from 'lucide-react'

import type { ToolMeta } from '../types'

/**
 * Developer Tools Registry
 * ══════════════════════════════════════════════════════════════════════════
 * All tools here run entirely in the browser (processingMode: 'browser').
 * These are the FIRST tools to be implemented in Sprint 4.
 * No backend required — pure JavaScript/TypeScript logic.
 * ══════════════════════════════════════════════════════════════════════════
 */

export const developerTools: ToolMeta[] = [
  {
    id: 'json-formatter',
    slug: 'json-formatter',
    title: 'JSON Formatter & Beautifier',
    shortTitle: 'JSON Formatter',
    description:
      'Format, beautify, and validate JSON data instantly. Supports pretty-print with custom indentation, minify mode, and syntax error detection.',
    shortDescription: 'Format, beautify, and validate JSON data.',
    category: 'developer',
    subcategory: 'formatting',
    icon: Braces,
    keywords: [
      'json formatter',
      'json beautifier',
      'format json',
      'json pretty print',
      'json validator',
      'json minifier',
      'json online',
    ],
    tags: ['json', 'format', 'beautify', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    isFeatured: true,
    seo: {
      title: 'JSON Formatter & Beautifier — Format JSON Online Free',
      description:
        'Format and beautify JSON data online. Pretty-print with custom indentation, validate JSON syntax, and minify JSON. Free, instant, no sign-up.',
      keywords: [
        'json formatter online free',
        'json beautifier',
        'format json online',
        'json pretty print',
        'json validator free',
      ],
    },
    relatedToolSlugs: ['json-validator', 'base64-encoder', 'jwt-decoder', 'url-encoder'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'json-validator',
    slug: 'json-validator',
    title: 'JSON Validator',
    shortTitle: 'JSON Validator',
    description:
      'Validate JSON syntax and check for errors in real time. Highlights invalid characters and shows the exact line and position of each error.',
    shortDescription: 'Validate JSON syntax and detect errors instantly.',
    category: 'developer',
    subcategory: 'validation',
    icon: CheckCircle2,
    keywords: [
      'json validator',
      'validate json',
      'check json',
      'json syntax checker',
      'json lint',
      'json error checker',
    ],
    tags: ['json', 'validate', 'lint', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    seo: {
      title: 'JSON Validator — Check JSON Syntax Online Free',
      description:
        'Validate JSON syntax online. Find errors, missing commas, or invalid characters instantly. Free JSON linter with line-by-line error highlighting.',
      keywords: [
        'json validator online free',
        'validate json syntax',
        'json lint online',
        'check json errors',
      ],
    },
    relatedToolSlugs: ['json-formatter', 'regex-tester', 'base64-encoder', 'jwt-decoder'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'jwt-decoder',
    slug: 'jwt-decoder',
    title: 'JWT Decoder',
    shortTitle: 'JWT Decoder',
    description:
      'Decode and inspect JSON Web Tokens instantly. View the header, payload, and signature. Verify expiration and claims without a secret key.',
    shortDescription: 'Decode and inspect JWT tokens — header, payload, signature.',
    category: 'developer',
    subcategory: 'security',
    icon: Key,
    keywords: [
      'jwt decoder',
      'decode jwt',
      'jwt parser',
      'json web token decoder',
      'jwt inspect',
      'jwt payload',
      'jwt header',
    ],
    tags: ['jwt', 'token', 'decode', 'security', 'developer'],
    difficulty: 'intermediate',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    seo: {
      title: 'JWT Decoder — Decode JSON Web Tokens Online Free',
      description:
        'Decode JWT tokens online. Inspect header, payload, and signature. Verify expiration and claims. Free, client-side — your token never leaves your browser.',
      keywords: [
        'jwt decoder online free',
        'decode json web token',
        'jwt parser',
        'jwt inspector',
        'jwt token viewer',
      ],
    },
    relatedToolSlugs: ['base64-encoder', 'json-formatter', 'hash-generator', 'json-validator'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'base64-encoder',
    slug: 'base64-encoder',
    title: 'Base64 Encoder / Decoder',
    shortTitle: 'Base64 Encoder',
    description:
      'Encode text or files to Base64 and decode Base64 strings back to their original form. Supports UTF-8, URL-safe Base64, and binary data.',
    shortDescription: 'Encode and decode Base64 strings instantly.',
    category: 'developer',
    subcategory: 'encoding',
    icon: Hash,
    keywords: [
      'base64 encoder',
      'base64 decoder',
      'encode base64',
      'decode base64',
      'base64 converter',
      'base64 online',
    ],
    tags: ['base64', 'encode', 'decode', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    isFeatured: true,
    seo: {
      title: 'Base64 Encoder & Decoder — Encode & Decode Online Free',
      description:
        'Encode text to Base64 or decode Base64 strings online. Supports URL-safe Base64. Free, instant, runs in your browser — data never leaves your device.',
      keywords: [
        'base64 encoder online free',
        'base64 decoder',
        'encode text base64',
        'decode base64 string',
        'base64 converter',
      ],
    },
    relatedToolSlugs: ['url-encoder', 'json-formatter', 'jwt-decoder', 'hash-generator'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'uuid-generator',
    slug: 'uuid-generator',
    title: 'UUID Generator',
    shortTitle: 'UUID Generator',
    description:
      'Generate cryptographically secure UUIDs (v4) instantly. Generate one or bulk generate up to 1000 UUIDs. Copy with one click. Runs entirely in your browser.',
    shortDescription: 'Generate cryptographically secure UUIDs (v4).',
    category: 'developer',
    subcategory: 'generation',
    icon: Fingerprint,
    keywords: [
      'uuid generator',
      'generate uuid',
      'guid generator',
      'uuid v4',
      'random uuid',
      'unique id generator',
    ],
    tags: ['uuid', 'guid', 'generate', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    isFeatured: true,
    seo: {
      title: 'UUID Generator — Generate UUIDs Online Free',
      description:
        'Generate cryptographically secure UUIDs (v4) online. Bulk generate up to 1000 UUIDs. Copy to clipboard. Free, instant, runs in your browser.',
      keywords: [
        'uuid generator online free',
        'generate uuid v4',
        'guid generator',
        'random uuid online',
        'bulk uuid generator',
      ],
    },
    relatedToolSlugs: ['password-generator', 'hash-generator', 'base64-encoder', 'json-formatter'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'hash-generator',
    slug: 'hash-generator',
    title: 'Hash Generator',
    shortTitle: 'Hash Generator',
    description:
      'Generate MD5, SHA-1, SHA-256, SHA-512 hashes from text or files. Verify file integrity by comparing hash values. Runs entirely in your browser.',
    shortDescription: 'Generate MD5, SHA-1, SHA-256, SHA-512 hashes.',
    category: 'developer',
    subcategory: 'security',
    icon: Shield,
    keywords: [
      'hash generator',
      'md5 generator',
      'sha256 generator',
      'sha1 hash',
      'sha512',
      'file hash',
      'checksum generator',
    ],
    tags: ['hash', 'md5', 'sha256', 'checksum', 'developer'],
    difficulty: 'intermediate',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Hash Generator — MD5, SHA-1, SHA-256, SHA-512 Online Free',
      description:
        'Generate cryptographic hashes online. Supports MD5, SHA-1, SHA-256, and SHA-512. Hash text or files. Verify file integrity. Free, runs in your browser.',
      keywords: [
        'hash generator online free',
        'md5 hash generator',
        'sha256 generator online',
        'sha1 hash online',
        'checksum calculator',
      ],
    },
    relatedToolSlugs: ['password-generator', 'uuid-generator', 'jwt-decoder', 'base64-encoder'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'regex-tester',
    slug: 'regex-tester',
    title: 'Regex Tester',
    shortTitle: 'Regex Tester',
    description:
      'Test and debug regular expressions in real time. Highlights all matches in your test string. Shows captured groups. Supports all JS regex flags.',
    shortDescription: 'Test and debug regular expressions in real time.',
    category: 'developer',
    subcategory: 'testing',
    icon: Search,
    keywords: [
      'regex tester',
      'regular expression tester',
      'regex validator',
      'regex matcher',
      'test regex',
      'regex debugger',
      'regex online',
    ],
    tags: ['regex', 'regexp', 'test', 'developer'],
    difficulty: 'intermediate',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    seo: {
      title: 'Regex Tester — Test Regular Expressions Online Free',
      description:
        'Test regular expressions online in real time. Highlights matches and captured groups. Supports all JavaScript regex flags. Free, instant.',
      keywords: [
        'regex tester online free',
        'regular expression tester',
        'regex validator',
        'test regex online',
        'regex debugger',
      ],
    },
    relatedToolSlugs: ['json-validator', 'json-formatter', 'url-encoder', 'html-encoder'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'url-encoder',
    slug: 'url-encoder',
    title: 'URL Encoder / Decoder',
    shortTitle: 'URL Encoder',
    description:
      'Encode and decode URLs and URL components. Convert special characters to percent-encoding and back. Useful for building query strings and APIs.',
    shortDescription: 'Encode and decode URLs and query parameters.',
    category: 'developer',
    subcategory: 'encoding',
    icon: Link,
    keywords: [
      'url encoder',
      'url decoder',
      'percent encoding',
      'url encode online',
      'url decode',
      'uri encoder',
      'query string encoder',
    ],
    tags: ['url', 'encode', 'decode', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'URL Encoder & Decoder — Encode URLs Online Free',
      description:
        'Encode or decode URLs and query parameters online. Convert special characters to percent-encoding. Free, instant, runs in your browser.',
      keywords: [
        'url encoder online free',
        'url decoder',
        'percent encode url',
        'encode url online',
        'uri decoder',
      ],
    },
    relatedToolSlugs: ['base64-encoder', 'html-encoder', 'json-formatter', 'regex-tester'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'html-encoder',
    slug: 'html-encoder',
    title: 'HTML Entity Encoder / Decoder',
    shortTitle: 'HTML Encoder',
    description:
      'Encode text to HTML entities and decode HTML entities back to text. Escape special characters like <, >, &, ", and \' for safe HTML output.',
    shortDescription: 'Encode and decode HTML entities.',
    category: 'developer',
    subcategory: 'encoding',
    icon: Code,
    keywords: [
      'html encoder',
      'html entity encoder',
      'html escape',
      'encode html',
      'html decoder',
      'html entities',
    ],
    tags: ['html', 'encode', 'entities', 'escape', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'HTML Encoder & Decoder — HTML Entity Converter Online Free',
      description:
        'Encode text to HTML entities or decode HTML entities online. Escape special characters for safe HTML. Free, instant, no sign-up.',
      keywords: [
        'html encoder online free',
        'html entity encoder',
        'html escape online',
        'decode html entities',
        'html character encoder',
      ],
    },
    relatedToolSlugs: ['url-encoder', 'base64-encoder', 'json-formatter', 'regex-tester'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'color-converter',
    slug: 'color-converter',
    title: 'Color Converter',
    shortTitle: 'Color Converter',
    description:
      'Convert colors between HEX, RGB, RGBA, HSL, HSLA, HSV, and CMYK formats. Real-time color preview. Copy any format with one click.',
    shortDescription: 'Convert colors between HEX, RGB, HSL, CMYK, and more.',
    category: 'developer',
    subcategory: 'conversion',
    icon: Palette,
    keywords: [
      'color converter',
      'hex to rgb',
      'rgb to hex',
      'hsl converter',
      'color code converter',
      'cmyk to rgb',
      'color format converter',
    ],
    tags: ['color', 'hex', 'rgb', 'hsl', 'developer', 'design'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Color Converter — HEX to RGB, HSL, CMYK Online Free',
      description:
        'Convert colors between HEX, RGB, HSL, HSLA, CMYK formats online. Real-time color preview. Free, instant, no sign-up required.',
      keywords: [
        'color converter online free',
        'hex to rgb converter',
        'rgb to hex online',
        'hsl color converter',
        'cmyk to rgb online',
      ],
    },
    relatedToolSlugs: ['css-gradient-generator', 'color-palette-generator', 'base64-encoder', 'url-encoder'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'timestamp-converter',
    slug: 'timestamp-converter',
    title: 'Unix Timestamp Converter',
    shortTitle: 'Timestamp Converter',
    description:
      'Convert Unix timestamps to human-readable dates and times. Convert dates to Unix timestamps. Supports milliseconds and multiple time zones.',
    shortDescription: 'Convert Unix timestamps to dates and vice versa.',
    category: 'developer',
    subcategory: 'conversion',
    icon: Clock,
    keywords: [
      'unix timestamp converter',
      'timestamp to date',
      'date to timestamp',
      'epoch converter',
      'unix time converter',
      'milliseconds converter',
    ],
    tags: ['timestamp', 'unix', 'date', 'epoch', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Unix Timestamp Converter — Epoch to Date Online Free',
      description:
        'Convert Unix timestamps to human-readable dates and vice versa. Supports milliseconds and multiple time zones. Free, instant, no sign-up.',
      keywords: [
        'unix timestamp converter free',
        'epoch to date online',
        'timestamp to date converter',
        'unix time converter',
      ],
    },
    relatedToolSlugs: ['json-formatter', 'base64-encoder', 'url-encoder', 'uuid-generator'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'markdown-preview',
    slug: 'markdown-preview',
    title: 'Markdown Previewer',
    shortTitle: 'Markdown Preview',
    description:
      'Write and preview Markdown in real time. See rendered HTML output side by side. Supports GitHub Flavored Markdown, code blocks, and tables.',
    shortDescription: 'Write and preview Markdown in real time.',
    category: 'developer',
    subcategory: 'preview',
    icon: Eye,
    keywords: [
      'markdown previewer',
      'markdown editor',
      'markdown to html',
      'markdown live preview',
      'github flavored markdown',
      'md preview',
    ],
    tags: ['markdown', 'preview', 'editor', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Markdown Previewer — Live Markdown Editor Online Free',
      description:
        'Preview Markdown in real time. Side-by-side editor and HTML preview. Supports GitHub Flavored Markdown, tables, and code blocks. Free, no sign-up.',
      keywords: [
        'markdown previewer online free',
        'markdown editor live preview',
        'markdown to html online',
        'github flavored markdown editor',
      ],
    },
    relatedToolSlugs: ['json-formatter', 'html-encoder', 'word-counter', 'text-compare'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },

  /* ── JSON Tools (Phase 2) ─────────────────────────────────────────────── */

  {
    id: 'json-minifier',
    slug: 'json-minifier',
    title: 'JSON Minifier',
    shortTitle: 'JSON Minifier',
    description:
      'Minify and compress JSON by removing whitespace, indentation, and newlines. Reduce JSON file size for production APIs and storage.',
    shortDescription: 'Minify and compress JSON to reduce file size.',
    category: 'developer',
    subcategory: 'formatting',
    icon: Minimize2,
    keywords: [
      'json minifier',
      'minify json',
      'compress json',
      'json compressor',
      'reduce json size',
      'json uglify',
    ],
    tags: ['json', 'minify', 'compress', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'JSON Minifier — Compress & Minify JSON Online Free',
      description:
        'Minify and compress JSON online. Remove whitespace and reduce file size instantly. Free JSON compressor — no upload, runs in your browser.',
      keywords: [
        'json minifier online free',
        'minify json online',
        'compress json',
        'json compressor',
        'reduce json file size',
      ],
    },
    relatedToolSlugs: ['json-formatter', 'json-validator', 'json-to-csv', 'json-compare'],
    createdAt: '2026-06-29',
    updatedAt: '2026-06-29',
  },
  {
    id: 'json-compare',
    slug: 'json-compare',
    title: 'JSON Compare',
    shortTitle: 'JSON Compare',
    description:
      'Compare two JSON objects side by side. Highlight added, removed, and changed keys and values. Find differences instantly.',
    shortDescription: 'Compare two JSON objects and highlight differences.',
    category: 'developer',
    subcategory: 'analysis',
    icon: GitCompare,
    keywords: [
      'json compare',
      'compare json',
      'json diff',
      'json difference',
      'json comparison tool',
      'compare json objects',
    ],
    tags: ['json', 'compare', 'diff', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'JSON Compare — Compare Two JSON Objects Online Free',
      description:
        'Compare two JSON objects online. Find added, removed, and changed values. Free JSON diff tool — no upload, runs in your browser.',
      keywords: [
        'json compare online free',
        'compare json objects',
        'json diff tool',
        'json difference checker',
        'json comparison',
      ],
    },
    relatedToolSlugs: ['json-formatter', 'json-validator', 'json-minifier', 'text-compare'],
    createdAt: '2026-06-29',
    updatedAt: '2026-06-29',
  },
  {
    id: 'json-to-yaml',
    slug: 'json-to-yaml',
    title: 'JSON to YAML Converter',
    shortTitle: 'JSON to YAML',
    description:
      'Convert JSON to YAML format instantly. Clean, human-readable YAML output. Supports nested objects, arrays, and all JSON data types.',
    shortDescription: 'Convert JSON to YAML format instantly.',
    category: 'developer',
    subcategory: 'conversion',
    icon: ArrowLeftRight,
    keywords: [
      'json to yaml',
      'convert json to yaml',
      'json yaml converter',
      'json to yml',
      'json yaml online',
    ],
    tags: ['json', 'yaml', 'convert', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'JSON to YAML Converter — Convert JSON to YAML Online Free',
      description:
        'Convert JSON to YAML online. Get clean, readable YAML output. Free, instant, no upload required — runs entirely in your browser.',
      keywords: [
        'json to yaml converter free',
        'convert json to yaml online',
        'json yaml online',
        'json to yml converter',
      ],
    },
    relatedToolSlugs: ['yaml-to-json', 'json-formatter', 'json-minifier', 'json-validator'],
    createdAt: '2026-06-29',
    updatedAt: '2026-06-29',
  },
  {
    id: 'yaml-to-json',
    slug: 'yaml-to-json',
    title: 'YAML to JSON Converter',
    shortTitle: 'YAML to JSON',
    description:
      'Convert YAML to JSON format instantly. Supports multi-document YAML, anchors, and aliases. Validates YAML syntax as you convert.',
    shortDescription: 'Convert YAML to JSON format instantly.',
    category: 'developer',
    subcategory: 'conversion',
    icon: Workflow,
    keywords: [
      'yaml to json',
      'convert yaml to json',
      'yaml json converter',
      'yml to json',
      'yaml parser online',
    ],
    tags: ['yaml', 'json', 'convert', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'YAML to JSON Converter — Convert YAML to JSON Online Free',
      description:
        'Convert YAML to JSON online. Parse YAML and get valid JSON output instantly. Free, no upload required — runs in your browser.',
      keywords: [
        'yaml to json converter free',
        'convert yaml to json online',
        'yml to json',
        'yaml json parser',
      ],
    },
    relatedToolSlugs: ['json-to-yaml', 'json-formatter', 'json-validator', 'json-minifier'],
    createdAt: '2026-06-29',
    updatedAt: '2026-06-29',
  },
  {
    id: 'json-to-csv',
    slug: 'json-to-csv',
    title: 'JSON to CSV Converter',
    shortTitle: 'JSON to CSV',
    description:
      'Convert JSON arrays to CSV format. Auto-detects columns from JSON keys. Download the CSV file or copy to clipboard.',
    shortDescription: 'Convert JSON arrays to CSV format.',
    category: 'developer',
    subcategory: 'conversion',
    icon: FileSpreadsheet,
    keywords: [
      'json to csv',
      'convert json to csv',
      'json csv converter',
      'export json as csv',
      'json table converter',
    ],
    tags: ['json', 'csv', 'convert', 'developer', 'data'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'JSON to CSV Converter — Convert JSON to CSV Online Free',
      description:
        'Convert JSON arrays to CSV format online. Auto-detect columns, download CSV. Free, instant, no upload required.',
      keywords: [
        'json to csv converter free',
        'convert json to csv online',
        'json csv export',
        'json to spreadsheet',
      ],
    },
    relatedToolSlugs: ['csv-to-json', 'json-formatter', 'json-validator', 'json-minifier'],
    createdAt: '2026-06-29',
    updatedAt: '2026-06-29',
  },
  {
    id: 'csv-to-json',
    slug: 'csv-to-json',
    title: 'CSV to JSON Converter',
    shortTitle: 'CSV to JSON',
    description:
      'Convert CSV data to JSON format. Uses the first row as headers. Supports custom delimiters. Output as array of objects or array of arrays.',
    shortDescription: 'Convert CSV data to JSON format.',
    category: 'developer',
    subcategory: 'conversion',
    icon: Braces,
    keywords: [
      'csv to json',
      'convert csv to json',
      'csv json converter',
      'csv parser online',
      'import csv as json',
    ],
    tags: ['csv', 'json', 'convert', 'developer', 'data'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'CSV to JSON Converter — Convert CSV to JSON Online Free',
      description:
        'Convert CSV files to JSON online. Parse CSV with headers and get JSON array output. Free, instant, runs in your browser.',
      keywords: [
        'csv to json converter free',
        'convert csv to json online',
        'csv json parser',
        'csv to json array',
      ],
    },
    relatedToolSlugs: ['json-to-csv', 'json-formatter', 'json-validator', 'json-minifier'],
    createdAt: '2026-06-29',
    updatedAt: '2026-06-29',
  },
  /* ── Sprint 7: New Developer Tools ───────────────────────────────────── */
  {
    id: 'number-base-converter',
    slug: 'number-base-converter',
    title: 'Number Base Converter',
    shortTitle: 'Base Converter',
    description:
      'Convert numbers between binary (base 2), octal (base 8), decimal (base 10), and hexadecimal (base 16) instantly. Essential tool for developers and students.',
    shortDescription: 'Convert numbers between binary, octal, decimal, and hex.',
    category: 'developer',
    subcategory: 'conversion',
    icon: Binary,
    keywords: ['number base converter', 'binary to decimal', 'hex converter', 'decimal to binary', 'base converter', 'hexadecimal converter', 'octal converter'],
    tags: ['binary', 'hex', 'decimal', 'octal', 'convert', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Number Base Converter — Binary, Octal, Decimal, Hex Free',
      description: 'Convert numbers between binary, octal, decimal, and hexadecimal online. Instant results, free, no sign-up required.',
      keywords: ['number base converter online free', 'binary to decimal converter', 'decimal to hex', 'binary hex octal decimal'],
    },
    relatedToolSlugs: ['binary-converter', 'hash-generator', 'uuid-generator', 'color-converter'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'cron-expression-parser',
    slug: 'cron-expression-parser',
    title: 'Cron Expression Parser',
    shortTitle: 'Cron Parser',
    description:
      'Parse and explain cron expressions in plain English. Understand what your cron job schedule means and see the next 5 scheduled run times.',
    shortDescription: 'Parse cron expressions and explain them in plain English.',
    category: 'developer',
    subcategory: 'utilities',
    icon: Clock,
    keywords: ['cron expression parser', 'cron job explainer', 'cron schedule parser', 'cron syntax', 'cron expression builder', 'crontab parser'],
    tags: ['cron', 'schedule', 'parse', 'developer', 'devops'],
    difficulty: 'intermediate',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Cron Expression Parser — Explain Cron Jobs Online Free',
      description: 'Parse cron expressions and get a plain English explanation. See next 5 scheduled run times. Free, instant, no sign-up.',
      keywords: ['cron expression parser online', 'cron job explainer', 'crontab parser free', 'cron schedule parser'],
    },
    relatedToolSlugs: ['timestamp-converter', 'date-calculator', 'regex-tester', 'json-formatter'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'html-formatter',
    slug: 'html-formatter',
    title: 'HTML Formatter & Beautifier',
    shortTitle: 'HTML Formatter',
    description:
      'Format and beautify HTML code with proper indentation. Prettify minified HTML for better readability. Supports nested elements and inline elements.',
    shortDescription: 'Format and beautify HTML code with proper indentation.',
    category: 'developer',
    subcategory: 'formatting',
    icon: Code,
    keywords: ['html formatter', 'html beautifier', 'format html', 'html pretty print', 'html indentation', 'html code formatter'],
    tags: ['html', 'format', 'beautify', 'developer', 'code'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'HTML Formatter & Beautifier — Format HTML Online Free',
      description: 'Format and beautify HTML code online. Proper indentation, clean output. Free, instant, runs in your browser.',
      keywords: ['html formatter online free', 'html beautifier', 'format html online', 'html code formatter'],
    },
    relatedToolSlugs: ['html-encoder', 'html-to-text', 'json-formatter', 'xml-formatter'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'xml-formatter',
    slug: 'xml-formatter',
    title: 'XML Formatter & Beautifier',
    shortTitle: 'XML Formatter',
    description:
      'Format and beautify XML code with proper indentation. Prettify minified or condensed XML for better readability. Validates structure while formatting.',
    shortDescription: 'Format and beautify XML code with proper indentation.',
    category: 'developer',
    subcategory: 'formatting',
    icon: FileCode,
    keywords: ['xml formatter', 'xml beautifier', 'format xml', 'xml pretty print', 'xml indentation', 'xml code formatter'],
    tags: ['xml', 'format', 'beautify', 'developer', 'code'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'XML Formatter & Beautifier — Format XML Online Free',
      description: 'Format and beautify XML code online. Proper indentation and structure. Free, instant, runs in your browser.',
      keywords: ['xml formatter online free', 'xml beautifier', 'format xml online', 'xml code formatter'],
    },
    relatedToolSlugs: ['html-formatter', 'json-formatter', 'xml-to-json', 'json-to-xml'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'xml-to-json',
    slug: 'xml-to-json',
    title: 'XML to JSON Converter',
    shortTitle: 'XML to JSON',
    description:
      'Convert XML to JSON format instantly. Parses XML structure including attributes, nested elements, and text content into valid JSON.',
    shortDescription: 'Convert XML to JSON format instantly.',
    category: 'developer',
    subcategory: 'conversion',
    icon: ArrowLeftRight,
    keywords: ['xml to json', 'convert xml to json', 'xml json converter', 'xml parser', 'xml to json online'],
    tags: ['xml', 'json', 'convert', 'developer', 'data'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'XML to JSON Converter — Convert XML to JSON Online Free',
      description: 'Convert XML to JSON online. Parse XML and get valid JSON output. Free, instant, runs in your browser.',
      keywords: ['xml to json converter free', 'convert xml to json online', 'xml json parser', 'xml to json array'],
    },
    relatedToolSlugs: ['json-to-xml', 'json-formatter', 'xml-formatter', 'yaml-to-json'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'json-to-xml',
    slug: 'json-to-xml',
    title: 'JSON to XML Converter',
    shortTitle: 'JSON to XML',
    description:
      'Convert JSON to XML format instantly. Transforms JSON objects, arrays, and nested structures into valid, well-formed XML markup.',
    shortDescription: 'Convert JSON to XML format instantly.',
    category: 'developer',
    subcategory: 'conversion',
    icon: Workflow,
    keywords: ['json to xml', 'convert json to xml', 'json xml converter', 'json to xml online'],
    tags: ['json', 'xml', 'convert', 'developer', 'data'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'JSON to XML Converter — Convert JSON to XML Online Free',
      description: 'Convert JSON to XML online. Transform JSON objects and arrays to XML. Free, instant, runs in your browser.',
      keywords: ['json to xml converter free', 'convert json to xml online', 'json xml online', 'json to xml generator'],
    },
    relatedToolSlugs: ['xml-to-json', 'json-formatter', 'xml-formatter', 'json-to-yaml'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'markdown-to-html',
    slug: 'markdown-to-html',
    title: 'Markdown to HTML Converter',
    shortTitle: 'Markdown to HTML',
    description:
      'Convert Markdown to HTML instantly. Supports headers, bold, italic, links, images, code blocks, lists, and tables. Get clean HTML output ready for web use.',
    shortDescription: 'Convert Markdown to HTML with full syntax support.',
    category: 'developer',
    subcategory: 'conversion',
    icon: Wand2,
    keywords: ['markdown to html', 'convert markdown to html', 'markdown html converter', 'md to html', 'markdown parser online'],
    tags: ['markdown', 'html', 'convert', 'developer', 'writing'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Markdown to HTML Converter — Convert MD to HTML Free',
      description: 'Convert Markdown to HTML online. Full syntax support: headers, links, code blocks, tables. Free, instant, runs in your browser.',
      keywords: ['markdown to html converter free', 'md to html online', 'markdown parser', 'markdown html generator'],
    },
    relatedToolSlugs: ['markdown-preview', 'html-formatter', 'html-to-text', 'json-formatter'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'css-minifier',
    slug: 'css-minifier',
    title: 'CSS Minifier',
    shortTitle: 'CSS Minifier',
    description:
      'Minify CSS code by removing comments, whitespace, and unnecessary characters. Reduces file size for faster page load times. Shows compression statistics.',
    shortDescription: 'Minify CSS code to reduce file size.',
    category: 'developer',
    subcategory: 'optimization',
    icon: Minimize2,
    keywords: ['css minifier', 'minify css', 'css compressor', 'css optimizer', 'compress css', 'css minification'],
    tags: ['css', 'minify', 'optimize', 'compress', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'CSS Minifier — Minify CSS Code Online Free',
      description: 'Minify CSS online. Remove comments and whitespace to reduce file size. Free, instant, runs in your browser.',
      keywords: ['css minifier online free', 'minify css online', 'css compressor', 'css optimizer free'],
    },
    relatedToolSlugs: ['json-minifier', 'json-formatter', 'html-formatter', 'xml-formatter'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'ip-address-validator',
    slug: 'ip-address-validator',
    title: 'IP Address Validator',
    shortTitle: 'IP Validator',
    description:
      'Validate IPv4 and IPv6 addresses. Detects the IP version, classifies type (loopback, private, public, multicast), and shows detailed information about the address.',
    shortDescription: 'Validate IPv4 and IPv6 addresses and see detailed info.',
    category: 'developer',
    subcategory: 'network',
    icon: Network,
    keywords: ['ip address validator', 'validate ip address', 'ipv4 validator', 'ipv6 validator', 'ip address checker', 'ip lookup'],
    tags: ['ip', 'network', 'validate', 'developer', 'ipv4', 'ipv6'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'IP Address Validator — Validate IPv4 & IPv6 Online Free',
      description: 'Validate IPv4 and IPv6 addresses online. Detect IP version, type, and class. Free, instant, no sign-up required.',
      keywords: ['ip address validator online free', 'validate ipv4 address', 'ip address checker', 'ipv6 validator online'],
    },
    relatedToolSlugs: ['regex-tester', 'hash-generator', 'url-encoder', 'uuid-generator'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  /* ── Sprint 8: New Developer Tools ───────────────────────────────────── */
  {
    id: 'css-beautifier',
    slug: 'css-beautifier',
    title: 'CSS Beautifier & Formatter',
    shortTitle: 'CSS Beautifier',
    description: 'Beautify and format CSS code with proper indentation. Convert minified or unformatted CSS into clean, readable code.',
    shortDescription: 'Beautify and format CSS code with proper indentation.',
    category: 'developer',
    subcategory: 'formatting',
    icon: Code,
    keywords: ['css beautifier', 'css formatter', 'format css', 'css pretty print', 'unminify css', 'css code formatter'],
    tags: ['css', 'beautify', 'format', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'CSS Beautifier — Format & Beautify CSS Online Free',
      description: 'Beautify and format CSS code online. Convert minified CSS to readable formatted code. Free, instant, no sign-up.',
      keywords: ['css beautifier online free', 'css formatter online', 'format css online', 'unminify css'],
    },
    relatedToolSlugs: ['css-minifier', 'html-formatter', 'json-formatter', 'xml-formatter'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'sql-formatter',
    slug: 'sql-formatter',
    title: 'SQL Formatter & Beautifier',
    shortTitle: 'SQL Formatter',
    description: 'Format and beautify SQL queries with proper indentation and keyword casing. Makes complex SQL queries readable and easier to debug.',
    shortDescription: 'Format SQL queries with proper indentation and keyword casing.',
    category: 'developer',
    subcategory: 'formatting',
    icon: FileText,
    keywords: ['sql formatter', 'sql beautifier', 'format sql', 'sql pretty print', 'sql query formatter', 'sql indenter'],
    tags: ['sql', 'format', 'beautify', 'database', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'SQL Formatter & Beautifier — Format SQL Online Free',
      description: 'Format and beautify SQL queries online. Proper indentation and keyword casing. Free, instant, no sign-up.',
      keywords: ['sql formatter online free', 'sql beautifier', 'format sql query online', 'sql query formatter free'],
    },
    relatedToolSlugs: ['json-formatter', 'csv-viewer', 'html-formatter', 'csv-to-json'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'svg-optimizer',
    slug: 'svg-optimizer',
    title: 'SVG Optimizer',
    shortTitle: 'SVG Optimizer',
    description: 'Optimize and minify SVG files by removing comments, metadata, unnecessary attributes, and whitespace. Reduces SVG file size without affecting appearance.',
    shortDescription: 'Optimize and minify SVG files to reduce file size.',
    category: 'developer',
    subcategory: 'optimization',
    icon: Minimize2,
    keywords: ['svg optimizer', 'svg minifier', 'optimize svg', 'compress svg', 'svg cleaner', 'svg minimizer'],
    tags: ['svg', 'optimize', 'minify', 'compress', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'SVG Optimizer — Optimize & Minify SVG Online Free',
      description: 'Optimize SVG files online. Remove comments, metadata, and whitespace to reduce file size. Free, instant, runs in browser.',
      keywords: ['svg optimizer online free', 'svg minifier', 'optimize svg file', 'compress svg online'],
    },
    relatedToolSlugs: ['css-minifier', 'html-minifier', 'json-minifier', 'html-formatter'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'html-minifier',
    slug: 'html-minifier',
    title: 'HTML Minifier',
    shortTitle: 'HTML Minifier',
    description: 'Minify HTML by removing comments, collapsing whitespace, and stripping unnecessary attributes. Reduces HTML file size for faster page loads.',
    shortDescription: 'Minify HTML to reduce file size for faster page loads.',
    category: 'developer',
    subcategory: 'optimization',
    icon: Minimize2,
    keywords: ['html minifier', 'minify html', 'html compressor', 'compress html', 'html optimizer', 'html minification'],
    tags: ['html', 'minify', 'compress', 'optimize', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'HTML Minifier — Minify HTML Code Online Free',
      description: 'Minify HTML online. Remove comments and collapse whitespace to reduce file size. Free, instant, runs in browser.',
      keywords: ['html minifier online free', 'minify html online', 'html compressor', 'html optimizer free'],
    },
    relatedToolSlugs: ['css-minifier', 'json-minifier', 'html-formatter', 'svg-optimizer'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'uuid-validator',
    slug: 'uuid-validator',
    title: 'UUID Validator',
    shortTitle: 'UUID Validator',
    description: 'Validate UUID format and detect version (v1, v2, v3, v4, v5). Checks if a string matches the standard UUID format (8-4-4-4-12 hexadecimal).',
    shortDescription: 'Validate UUID format and detect version.',
    category: 'developer',
    subcategory: 'validation',
    icon: CheckCircle2,
    keywords: ['uuid validator', 'validate uuid', 'uuid format checker', 'uuid version detector', 'guid validator', 'uuid checker'],
    tags: ['uuid', 'validate', 'guid', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'UUID Validator — Validate UUID Format Online Free',
      description: 'Validate UUID format online. Detect UUID version (v1-v5) and variant. Free, instant, no sign-up.',
      keywords: ['uuid validator online free', 'validate uuid format', 'guid validator', 'uuid version checker'],
    },
    relatedToolSlugs: ['uuid-generator', 'uuid-decoder', 'hash-generator', 'regex-tester'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'uuid-decoder',
    slug: 'uuid-decoder',
    title: 'UUID Decoder & Analyzer',
    shortTitle: 'UUID Decoder',
    description: 'Decode and analyze UUID structure. Shows version, variant, and for version 1 UUIDs: the embedded timestamp and node ID.',
    shortDescription: 'Decode UUID structure and extract embedded information.',
    category: 'developer',
    subcategory: 'utilities',
    icon: Fingerprint,
    keywords: ['uuid decoder', 'uuid analyzer', 'decode uuid', 'uuid version 1 timestamp', 'uuid info', 'guid decoder'],
    tags: ['uuid', 'decode', 'analyze', 'guid', 'developer'],
    difficulty: 'intermediate',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'UUID Decoder & Analyzer — Decode UUID Online Free',
      description: 'Decode UUID and see version, variant, embedded timestamp (v1). Free, instant, no sign-up.',
      keywords: ['uuid decoder online free', 'decode uuid online', 'uuid analyzer', 'uuid version 1 timestamp decoder'],
    },
    relatedToolSlugs: ['uuid-generator', 'uuid-validator', 'hash-generator', 'timestamp-converter'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'extract-emails',
    slug: 'extract-emails',
    title: 'Email Extractor',
    shortTitle: 'Extract Emails',
    description: 'Extract all email addresses from any text. Paste a document, webpage source, or any content and instantly get a clean list of all email addresses found.',
    shortDescription: 'Extract all email addresses from any text content.',
    category: 'developer',
    subcategory: 'utilities',
    icon: Search,
    keywords: ['email extractor', 'extract emails from text', 'email finder', 'find email addresses', 'email scraper', 'extract email addresses'],
    tags: ['email', 'extract', 'finder', 'text', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Email Extractor — Extract Emails from Text Online Free',
      description: 'Extract all email addresses from any text. Paste content and get a clean email list. Free, instant, no sign-up.',
      keywords: ['email extractor online free', 'extract emails from text', 'email address finder', 'find emails in text'],
    },
    relatedToolSlugs: ['regex-tester', 'text-statistics', 'keyword-density', 'word-counter'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'html-preview',
    slug: 'html-preview',
    title: 'HTML Live Preview',
    shortTitle: 'HTML Preview',
    description: 'Preview HTML code in real time. Paste or type HTML and see the rendered output instantly. Useful for testing HTML snippets without a local editor.',
    shortDescription: 'Preview HTML code rendered in real time.',
    category: 'developer',
    subcategory: 'utilities',
    icon: Eye,
    keywords: ['html preview', 'html viewer', 'html live preview', 'render html online', 'html tester', 'online html editor'],
    tags: ['html', 'preview', 'render', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'HTML Live Preview — Preview HTML Online Free',
      description: 'Preview HTML code rendered in real time. Paste HTML and see the output instantly. Free, no sign-up.',
      keywords: ['html preview online free', 'html viewer online', 'html live preview', 'render html online'],
    },
    relatedToolSlugs: ['html-formatter', 'html-minifier', 'html-encoder', 'markdown-preview'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'diff-checker',
    slug: 'diff-checker',
    title: 'Diff Checker',
    shortTitle: 'Diff Checker',
    description: 'Compare two texts and highlight differences line by line. See added lines (green), removed lines (red), and unchanged lines. Perfect for code and document comparison.',
    shortDescription: 'Compare two texts and highlight line-by-line differences.',
    category: 'developer',
    subcategory: 'comparison',
    icon: GitCompare,
    keywords: ['diff checker', 'text diff', 'compare code', 'line diff', 'text comparison', 'code diff tool', 'diff tool online'],
    tags: ['diff', 'compare', 'text', 'code', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    seo: {
      title: 'Diff Checker — Compare Two Texts Online Free',
      description: 'Compare two texts and highlight differences. See added, removed, and unchanged lines. Free, instant, no sign-up.',
      keywords: ['diff checker online free', 'text diff tool', 'compare two texts online', 'code diff online'],
    },
    relatedToolSlugs: ['text-compare', 'json-compare', 'remove-duplicate-lines', 'word-counter'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'barcode-generator',
    slug: 'barcode-generator',
    title: 'Barcode Generator',
    shortTitle: 'Barcode Generator',
    description: 'Generate barcodes in multiple formats: Code 128, Code 39, EAN-13, and UPC. Download as PNG image. Perfect for product labeling and inventory management.',
    shortDescription: 'Generate barcodes in Code 128, Code 39, EAN-13, and UPC formats.',
    category: 'developer',
    subcategory: 'generator',
    icon: Barcode,
    keywords: ['barcode generator', 'create barcode', 'barcode maker', 'code 128 generator', 'ean13 generator', 'upc barcode generator'],
    tags: ['barcode', 'generate', 'code128', 'ean', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    seo: {
      title: 'Barcode Generator — Create Barcodes Online Free',
      description: 'Generate barcodes online. Code 128, Code 39, EAN-13, UPC. Download as PNG. Free, instant, no sign-up.',
      keywords: ['barcode generator online free', 'create barcode online', 'code 128 generator', 'ean13 barcode generator'],
    },
    relatedToolSlugs: ['qr-code-generator', 'placeholder-image-generator', 'favicon-generator'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'unix-time-now',
    slug: 'unix-time-now',
    title: 'Unix Timestamp — Live',
    shortTitle: 'Unix Time Now',
    description: 'See the current Unix timestamp updating in real time. View the current time in Unix seconds, milliseconds, ISO 8601, UTC, and local formats. Also convert any Unix timestamp.',
    shortDescription: 'Live Unix timestamp with real-time updates and format converter.',
    category: 'developer',
    subcategory: 'time',
    icon: Clock,
    keywords: ['unix timestamp', 'current unix time', 'epoch time now', 'unix time converter', 'current epoch', 'unix timestamp now'],
    tags: ['unix', 'timestamp', 'epoch', 'time', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    seo: {
      title: 'Unix Timestamp Now — Live Epoch Time & Converter Free',
      description: 'See current Unix timestamp live. Convert between Unix epoch and human-readable dates. Free, real-time, no sign-up.',
      keywords: ['unix timestamp now online', 'current epoch time', 'unix time converter online', 'epoch timestamp live'],
    },
    relatedToolSlugs: ['timestamp-converter', 'date-calculator', 'cron-expression-parser', 'uuid-decoder'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'color-contrast-checker',
    slug: 'color-contrast-checker',
    title: 'Color Contrast Checker',
    shortTitle: 'Contrast Checker',
    description: 'Check WCAG color contrast ratios between foreground and background colors. Instantly see if your color combination meets AA or AAA accessibility standards.',
    shortDescription: 'Check WCAG AA/AAA color contrast ratios for accessibility.',
    category: 'developer',
    subcategory: 'accessibility',
    icon: Contrast,
    keywords: ['color contrast checker', 'wcag contrast', 'accessibility contrast', 'contrast ratio calculator', 'aa aaa contrast', 'color accessibility checker'],
    tags: ['contrast', 'wcag', 'accessibility', 'color', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Color Contrast Checker — WCAG AA/AAA Compliance Free',
      description: 'Check WCAG color contrast ratios online. See if colors meet AA or AAA accessibility standards. Free, instant.',
      keywords: ['color contrast checker online free', 'wcag contrast checker', 'accessibility contrast tool', 'aa aaa contrast calculator'],
    },
    relatedToolSlugs: ['color-converter', 'color-palette-generator', 'css-gradient-generator'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'password-strength-checker',
    slug: 'password-strength-checker',
    title: 'Password Strength Checker',
    shortTitle: 'Password Strength',
    description: 'Check how strong your password is. Analyzes length, character variety, and common patterns. Shows strength rating and estimated crack time. Runs entirely in your browser.',
    shortDescription: 'Analyze password strength, character variety, and crack time.',
    category: 'developer',
    subcategory: 'security',
    icon: Shield,
    keywords: ['password strength checker', 'password strength tester', 'how strong is my password', 'password security checker', 'check password strength'],
    tags: ['password', 'security', 'strength', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Password Strength Checker — Test Password Security Free',
      description: 'Check password strength online. See strength rating, character analysis, and estimated crack time. Runs in browser. Free.',
      keywords: ['password strength checker online free', 'check password strength', 'password security tester', 'how strong is my password online'],
    },
    relatedToolSlugs: ['password-generator', 'hash-generator', 'uuid-generator'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'json-to-table',
    slug: 'json-to-table',
    title: 'JSON to Table',
    shortTitle: 'JSON Table',
    description: 'Convert a JSON array to a readable table. Paste a JSON array of objects and view the data in an organized, sortable table format.',
    shortDescription: 'Convert JSON arrays to a visual data table.',
    category: 'developer',
    subcategory: 'data',
    icon: Table,
    keywords: ['json to table', 'json table viewer', 'json array to table', 'visualize json', 'json data table', 'json viewer'],
    tags: ['json', 'table', 'data', 'visualize', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'JSON to Table — Convert JSON Array to Table Online Free',
      description: 'Convert JSON arrays to a visual table online. View JSON data in organized table format. Free, instant, no sign-up.',
      keywords: ['json to table online free', 'json table viewer', 'json array to table', 'visualize json data'],
    },
    relatedToolSlugs: ['csv-viewer', 'json-formatter', 'json-to-csv', 'csv-to-json'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'csv-viewer',
    slug: 'csv-viewer',
    title: 'CSV Viewer',
    shortTitle: 'CSV Viewer',
    description: 'View CSV data as a formatted table. Paste CSV content and instantly see it as a clean, organized table. Handles quoted fields, commas inside values, and empty cells.',
    shortDescription: 'View CSV data as a formatted table.',
    category: 'developer',
    subcategory: 'data',
    icon: FileSpreadsheet,
    keywords: ['csv viewer', 'view csv online', 'csv to table', 'csv reader', 'csv parser online', 'csv data viewer'],
    tags: ['csv', 'table', 'data', 'viewer', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    seo: {
      title: 'CSV Viewer — View CSV as Table Online Free',
      description: 'View CSV data as a formatted table online. Handles quoted fields and complex CSV. Free, instant, no sign-up.',
      keywords: ['csv viewer online free', 'view csv online', 'csv to table online', 'csv reader free'],
    },
    relatedToolSlugs: ['json-to-table', 'csv-to-json', 'json-to-csv', 'json-formatter'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
]



