import {
  Dices,
  Image,
  Layers,
  Palette,
  QrCode,
  Scan,
  Shield,
  Wand2,
} from 'lucide-react'

import type { ToolMeta } from '../types'

/**
 * Generator Tools Registry
 * ══════════════════════════════════════════════════════════════════════════
 * Tools that generate useful content, codes, or design assets.
 * Most run in the browser. QR code generation may need a library.
 * ══════════════════════════════════════════════════════════════════════════
 */

export const generatorTools: ToolMeta[] = [
  {
    id: 'password-generator',
    slug: 'password-generator',
    title: 'Password Generator',
    shortTitle: 'Password Generator',
    description:
      'Generate cryptographically secure passwords. Customize length, character sets (uppercase, lowercase, numbers, symbols). Copy with one click. Never stored.',
    shortDescription: 'Generate strong, secure passwords instantly.',
    category: 'generator',
    subcategory: 'security',
    icon: Shield,
    keywords: [
      'password generator',
      'secure password generator',
      'random password generator',
      'strong password',
      'password creator',
      'generate password',
    ],
    tags: ['password', 'security', 'generate', 'random'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    isFeatured: true,
    seo: {
      title: 'Password Generator — Generate Secure Passwords Free',
      description:
        'Generate strong, secure passwords online. Customize length and character types. Copy instantly. Runs in your browser — passwords are never stored.',
      keywords: [
        'password generator online free',
        'secure password generator',
        'random password creator',
        'strong password generator',
        'generate secure password',
      ],
    },
    relatedToolSlugs: ['uuid-generator', 'hash-generator', 'base64-encoder', 'qr-code-generator'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'qr-code-generator',
    slug: 'qr-code-generator',
    title: 'QR Code Generator',
    shortTitle: 'QR Code Generator',
    description:
      'Generate QR codes for URLs, text, email, phone numbers, and WiFi credentials. Customize colors and size. Download as PNG or SVG.',
    shortDescription: 'Generate QR codes for URLs, text, and more.',
    category: 'generator',
    subcategory: 'utility',
    icon: QrCode,
    keywords: [
      'qr code generator',
      'generate qr code',
      'qr code creator',
      'qr code maker',
      'url qr code',
      'wifi qr code',
      'free qr code',
    ],
    tags: ['qr code', 'generate', 'url', 'wifi'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    isFeatured: true,
    isNew: true,
    seo: {
      title: 'QR Code Generator — Free QR Code Maker Online',
      description:
        'Generate QR codes for free online. Create QR codes for URLs, text, email, phone, and WiFi. Download as PNG or SVG. No sign-up required.',
      keywords: [
        'qr code generator free online',
        'create qr code',
        'qr code maker',
        'url qr code generator',
        'wifi qr code generator',
      ],
    },
    relatedToolSlugs: ['password-generator', 'uuid-generator', 'color-palette-generator', 'base64-encoder'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'color-palette-generator',
    slug: 'color-palette-generator',
    title: 'Color Palette Generator',
    shortTitle: 'Color Palette',
    description:
      'Generate beautiful color palettes from a seed color. Explore complementary, analogous, triadic, and monochromatic color schemes. Export as CSS, JSON, or hex codes.',
    shortDescription: 'Generate color palettes from any seed color.',
    category: 'generator',
    subcategory: 'design',
    icon: Palette,
    keywords: [
      'color palette generator',
      'color scheme generator',
      'color palette maker',
      'complementary colors',
      'color combinations',
      'design colors',
    ],
    tags: ['color', 'palette', 'design', 'generate'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Color Palette Generator — Create Color Schemes Free',
      description:
        'Generate color palettes online for free. Create complementary, analogous, triadic color schemes. Export as CSS or hex codes. Perfect for designers.',
      keywords: [
        'color palette generator free',
        'color scheme generator',
        'complementary color generator',
        'color combination tool',
      ],
    },
    relatedToolSlugs: ['css-gradient-generator', 'color-converter', 'qr-code-generator', 'password-generator'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'css-gradient-generator',
    slug: 'css-gradient-generator',
    title: 'CSS Gradient Generator',
    shortTitle: 'CSS Gradient',
    description:
      'Generate CSS linear, radial, and conic gradients visually. Add multiple color stops, control angles and positions. Copy the CSS code instantly.',
    shortDescription: 'Generate CSS gradients with visual preview.',
    category: 'generator',
    subcategory: 'design',
    icon: Layers,
    keywords: [
      'css gradient generator',
      'linear gradient generator',
      'radial gradient css',
      'gradient maker',
      'css background gradient',
      'gradient color tool',
    ],
    tags: ['css', 'gradient', 'design', 'developer'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'CSS Gradient Generator — Create CSS Gradients Free',
      description:
        'Generate CSS linear, radial, and conic gradients online. Visual gradient editor with multiple color stops. Copy CSS code instantly. Free, no sign-up.',
      keywords: [
        'css gradient generator free',
        'linear gradient generator',
        'css background gradient maker',
        'radial gradient online',
      ],
    },
    relatedToolSlugs: ['color-palette-generator', 'color-converter', 'qr-code-generator', 'password-generator'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'favicon-generator',
    slug: 'favicon-generator',
    title: 'Favicon Generator',
    shortTitle: 'Favicon Generator',
    description:
      'Generate favicon files from any image or text. Outputs all required sizes (16×16, 32×32, 48×48, 180×180) plus ICO, PNG, and SVG formats for all browsers.',
    shortDescription: 'Generate favicons in all required sizes and formats.',
    category: 'generator',
    subcategory: 'design',
    icon: Scan,
    keywords: [
      'favicon generator',
      'create favicon',
      'favicon maker',
      'website icon generator',
      'favicon ico generator',
      'pwa icons',
    ],
    tags: ['favicon', 'icon', 'design', 'web'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Favicon Generator — Create Favicons Online Free',
      description:
        'Generate favicons in all required sizes from any image. Get ICO, PNG, and SVG files. Supports Apple Touch icons and PWA icons. Free, no sign-up.',
      keywords: [
        'favicon generator free online',
        'create favicon from image',
        'favicon maker',
        'ico generator online',
      ],
    },
    relatedToolSlugs: ['color-palette-generator', 'css-gradient-generator', 'qr-code-generator', 'image-resize'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'lorem-ipsum-generator',
    slug: 'lorem-ipsum-generator',
    title: 'Advanced Lorem Ipsum Generator',
    shortTitle: 'Lorem Ipsum Pro',
    description:
      'Generate Lorem Ipsum text with advanced options. Choose between classic Lorem Ipsum, random words, or custom word lists. Control exact word, sentence, and paragraph counts.',
    shortDescription: 'Advanced placeholder text generator with custom options.',
    category: 'generator',
    subcategory: 'content',
    icon: Wand2,
    keywords: [
      'lorem ipsum generator',
      'placeholder text generator',
      'dummy text',
      'lorem ipsum advanced',
      'custom placeholder text',
      'generate filler text',
    ],
    tags: ['lorem ipsum', 'placeholder', 'text', 'generate'],
    difficulty: 'beginner',
    status: 'coming-soon',
    processingMode: 'browser',
    seo: {
      title: 'Lorem Ipsum Generator — Advanced Placeholder Text Tool',
      description:
        'Generate Lorem Ipsum text with advanced controls. Set exact word, sentence, and paragraph counts. Classic or custom word lists. Free, instant.',
      keywords: [
        'advanced lorem ipsum generator',
        'placeholder text generator',
        'custom lorem ipsum',
        'dummy text generator',
      ],
    },
    relatedToolSlugs: ['word-counter', 'character-counter', 'password-generator', 'qr-code-generator'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  /* ── Sprint 7: New Generator Tools ──────────────────────────────── */
  {
    id: 'random-number-generator',
    slug: 'random-number-generator',
    title: 'Random Number Generator',
    shortTitle: 'Random Numbers',
    description:
      'Generate random numbers between any min and max values. Generate multiple numbers at once, ensure uniqueness, or include decimals. Perfect for games, contests, and testing.',
    shortDescription: 'Generate random numbers between any min and max.',
    category: 'generator',
    subcategory: 'random',
    icon: Dices,
    keywords: ['random number generator', 'random number picker', 'generate random numbers', 'lottery number generator', 'random number between 1 and 100'],
    tags: ['random', 'number', 'generate', 'lottery', 'dice'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    seo: {
      title: 'Random Number Generator — Generate Random Numbers Free',
      description: 'Generate random numbers online. Set min/max, quantity, unique mode, and decimals. Perfect for contests and games. Free, instant.',
      keywords: ['random number generator online free', 'random number picker', 'generate random numbers', 'lottery number generator'],
    },
    relatedToolSlugs: ['uuid-generator', 'password-generator', 'hash-generator', 'qr-code-generator'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'placeholder-image-generator',
    slug: 'placeholder-image-generator',
    title: 'Placeholder Image Generator',
    shortTitle: 'Placeholder Image',
    description:
      'Generate custom placeholder images for mockups and prototypes. Set dimensions, background color, text color, and custom text. Download as PNG or JPEG instantly.',
    shortDescription: 'Generate custom placeholder images for mockups and prototypes.',
    category: 'generator',
    subcategory: 'design',
    icon: Image,
    keywords: ['placeholder image generator', 'dummy image generator', 'image placeholder', 'mockup image generator', 'test image generator'],
    tags: ['placeholder', 'image', 'mockup', 'generate', 'design'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Placeholder Image Generator — Create Dummy Images Free',
      description: 'Generate placeholder images for mockups online. Set dimensions, colors, and text. Download PNG or JPEG. Free, instant, no sign-up.',
      keywords: ['placeholder image generator free', 'dummy image generator', 'mockup image creator', 'test image generator online'],
    },
    relatedToolSlugs: ['favicon-generator', 'qr-code-generator', 'css-gradient-generator', 'color-palette-generator'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
]

