import {
  Contrast,
  Crop,
  Eraser,
  Expand,
  FileCode,
  FlipHorizontal,
  ImageDown,
  RefreshCw,
  RotateCw,
  SunDim,
  Type,
} from 'lucide-react'

import type { ToolMeta } from '../types'

/**
 * Image Tools Registry
 * ══════════════════════════════════════════════════════════════════════════
 * Most tools here require server-side processing via the `sharp` library.
 * Exception: image-to-base64 runs entirely in the browser.
 * Implementation target: Sprint 10.
 * ══════════════════════════════════════════════════════════════════════════
 */

export const imageTools: ToolMeta[] = [
  {
    id: 'image-compress',
    slug: 'image-compress',
    title: 'Image Compressor',
    shortTitle: 'Compress Image',
    description:
      'Compress JPG, PNG, WebP, and GIF images without visible quality loss. Reduce file size by up to 90% for faster websites and smaller uploads.',
    shortDescription: 'Compress images without visible quality loss.',
    category: 'image',
    subcategory: 'optimization',
    icon: ImageDown,
    keywords: [
      'compress image',
      'image compressor',
      'reduce image size',
      'jpg compressor',
      'png compressor',
      'optimize image',
      'image optimizer',
      'compress photo',
    ],
    tags: ['compress', 'optimize', 'jpg', 'png', 'webp'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'server',
    isPopular: true,
    isFeatured: true,
    supportedInputFormats: ['.jpg', '.jpeg', '.png', '.webp', '.gif'],
    supportedOutputFormats: ['.jpg', '.png', '.webp'],
    maxFileSizeMb: 50,
    seo: {
      title: 'Compress Images Online — Free Image Compressor',
      description:
        'Compress JPG, PNG, WebP images online for free. Reduce file size up to 90% without quality loss. Perfect for websites, email, and social media.',
      keywords: [
        'compress image online free',
        'image compressor',
        'reduce image file size',
        'jpg compressor online',
        'png compressor',
      ],
    },
    relatedToolSlugs: ['image-resize', 'image-convert', 'pdf-compress', 'image-to-base64'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'image-resize',
    slug: 'image-resize',
    title: 'Image Resizer',
    shortTitle: 'Resize Image',
    description:
      'Resize images by exact pixels, percentage, or preset dimensions. Maintain aspect ratio automatically. Supports JPG, PNG, and WebP formats.',
    shortDescription: 'Resize images by pixels, percentage, or preset sizes.',
    category: 'image',
    subcategory: 'editing',
    icon: Expand,
    keywords: [
      'resize image',
      'image resizer',
      'scale image',
      'change image size',
      'image dimensions',
      'resize photo',
      'image width height',
    ],
    tags: ['resize', 'dimensions', 'scale', 'image'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'server',
    isPopular: true,
    supportedInputFormats: ['.jpg', '.jpeg', '.png', '.webp', '.gif'],
    supportedOutputFormats: ['.jpg', '.png', '.webp'],
    maxFileSizeMb: 50,
    seo: {
      title: 'Resize Image Online — Free Image Resizer Tool',
      description:
        'Resize images online for free. Set exact pixel dimensions or scale by percentage. Maintain aspect ratio. Supports JPG, PNG, WebP.',
      keywords: [
        'resize image online free',
        'image resizer',
        'change image dimensions',
        'scale image online',
        'photo resizer',
      ],
    },
    relatedToolSlugs: ['image-compress', 'image-crop', 'image-convert', 'image-rotate'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'image-crop',
    slug: 'image-crop',
    title: 'Image Cropper',
    shortTitle: 'Crop Image',
    description:
      'Crop images with a drag-and-drop interface. Set custom crop dimensions, use preset aspect ratios (1:1, 16:9, 4:3), or free-form crop.',
    shortDescription: 'Crop images with custom dimensions or preset ratios.',
    category: 'image',
    subcategory: 'editing',
    icon: Crop,
    keywords: [
      'crop image',
      'image cropper',
      'cut image',
      'image crop tool',
      'crop photo',
      'aspect ratio crop',
    ],
    tags: ['crop', 'trim', 'aspect ratio', 'image'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    supportedInputFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    supportedOutputFormats: ['.jpg', '.png', '.webp'],
    maxFileSizeMb: 50,
    seo: {
      title: 'Crop Image Online — Free Image Cropping Tool',
      description:
        'Crop images online for free. Set custom dimensions, use aspect ratios, or free-form crop. No sign-up required. Works in your browser.',
      keywords: ['crop image online free', 'image cropper', 'crop photo online', 'cut image online'],
    },
    relatedToolSlugs: ['image-resize', 'image-rotate', 'image-compress', 'image-flip'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'image-rotate',
    slug: 'image-rotate',
    title: 'Rotate Image',
    shortTitle: 'Rotate Image',
    description:
      'Rotate images by 90°, 180°, or 270° clockwise or counter-clockwise. Straighten photos taken at wrong angles instantly.',
    shortDescription: 'Rotate images by 90°, 180°, or any custom angle.',
    category: 'image',
    subcategory: 'editing',
    icon: RotateCw,
    keywords: [
      'rotate image',
      'image rotation',
      'rotate photo',
      'turn image',
      'image orientation',
      'rotate jpg',
    ],
    tags: ['rotate', 'orientation', 'image'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'server',
    supportedInputFormats: ['.jpg', '.jpeg', '.png', '.webp', '.gif'],
    supportedOutputFormats: ['.jpg', '.png', '.webp'],
    maxFileSizeMb: 50,
    seo: {
      title: 'Rotate Image Online — Free Image Rotation Tool',
      description:
        'Rotate images online for free. Rotate by 90, 180, or 270 degrees. Fix photo orientation instantly. Supports JPG, PNG, WebP.',
      keywords: ['rotate image online free', 'rotate photo', 'image rotation tool', 'turn image online'],
    },
    relatedToolSlugs: ['image-flip', 'image-crop', 'image-resize', 'image-compress'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'image-convert',
    slug: 'image-convert',
    title: 'Image Converter',
    shortTitle: 'Convert Image',
    description:
      'Convert images between JPG, PNG, WebP, GIF, AVIF, and other formats. Batch convert multiple files at once. Preserve quality during conversion.',
    shortDescription: 'Convert images between JPG, PNG, WebP, and more.',
    category: 'image',
    subcategory: 'conversion',
    icon: RefreshCw,
    keywords: [
      'convert image',
      'image converter',
      'jpg to png',
      'png to jpg',
      'webp converter',
      'image format converter',
      'convert photo format',
    ],
    tags: ['convert', 'format', 'jpg', 'png', 'webp', 'image'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    supportedInputFormats: ['.jpg', '.jpeg', '.png', '.webp', '.gif', '.bmp', '.tiff', '.avif'],
    supportedOutputFormats: ['.jpg', '.png', '.webp', '.gif', '.avif'],
    maxFileSizeMb: 50,
    seo: {
      title: 'Image Converter — Convert JPG, PNG, WebP Online Free',
      description:
        'Convert images between JPG, PNG, WebP, GIF, and AVIF formats online. Free batch converter. No quality loss. No registration required.',
      keywords: [
        'image converter online free',
        'jpg to png converter',
        'png to jpg online',
        'webp converter',
        'convert image format',
      ],
    },
    relatedToolSlugs: ['image-compress', 'image-resize', 'pdf-to-image', 'image-to-base64'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'image-background-remover',
    slug: 'image-background-remover',
    title: 'Background Remover',
    shortTitle: 'Remove Background',
    description:
      'Remove image backgrounds automatically with AI. Get a clean transparent PNG in seconds. Perfect for product photos, portraits, and logos.',
    shortDescription: 'Remove image backgrounds automatically with AI.',
    category: 'image',
    subcategory: 'ai-editing',
    icon: Eraser,
    keywords: [
      'remove background',
      'background remover',
      'transparent background',
      'remove image background',
      'background eraser',
      'cut out background',
    ],
    tags: ['background', 'ai', 'transparent', 'remove', 'image'],
    difficulty: 'beginner',
    status: 'coming-soon',
    processingMode: 'server',
    isPopular: true,
    isFeatured: true,
    isNew: true,
    supportedInputFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    supportedOutputFormats: ['.png'],
    maxFileSizeMb: 20,
    seo: {
      title: 'Remove Image Background Online — Free AI Background Remover',
      description:
        'Remove image background automatically with AI. Get transparent PNG in seconds. Free online tool. Perfect for product photos and portraits.',
      keywords: [
        'remove background online free',
        'background remover',
        'ai background removal',
        'transparent background maker',
        'remove photo background',
      ],
    },
    relatedToolSlugs: ['image-compress', 'image-convert', 'image-resize', 'image-watermark'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'image-watermark',
    slug: 'image-watermark',
    title: 'Image Watermark',
    shortTitle: 'Watermark Image',
    description:
      'Add text or image watermarks to your photos. Customize font, size, color, opacity, and position. Batch watermark multiple images at once.',
    shortDescription: 'Add text or image watermarks to photos.',
    category: 'image',
    subcategory: 'editing',
    icon: Type,
    keywords: [
      'watermark image',
      'add watermark to image',
      'image watermark tool',
      'text watermark photo',
      'logo watermark image',
    ],
    tags: ['watermark', 'branding', 'text', 'image'],
    difficulty: 'intermediate',
    status: 'active',
    processingMode: 'browser',
    supportedInputFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    supportedOutputFormats: ['.jpg', '.png', '.webp'],
    maxFileSizeMb: 50,
    seo: {
      title: 'Add Watermark to Image Online — Free Photo Watermark Tool',
      description:
        'Add custom text or image watermarks to photos online. Free tool. Control position, opacity, font, and size. No sign-up required.',
      keywords: [
        'add watermark to image free',
        'image watermark online',
        'text watermark photo',
        'photo watermark tool',
      ],
    },
    relatedToolSlugs: ['image-compress', 'image-resize', 'pdf-watermark', 'image-background-remover'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'image-flip',
    slug: 'image-flip',
    title: 'Flip Image',
    shortTitle: 'Flip Image',
    description:
      'Flip images horizontally or vertically. Mirror photos instantly for social media, design work, or correcting camera orientation.',
    shortDescription: 'Flip images horizontally or vertically.',
    category: 'image',
    subcategory: 'editing',
    icon: FlipHorizontal,
    keywords: ['flip image', 'mirror image', 'flip photo', 'horizontal flip', 'vertical flip', 'mirror photo'],
    tags: ['flip', 'mirror', 'image'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'server',
    supportedInputFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    supportedOutputFormats: ['.jpg', '.png', '.webp'],
    maxFileSizeMb: 50,
    seo: {
      title: 'Flip Image Online — Mirror Photos Horizontally or Vertically',
      description:
        'Flip images horizontally or vertically online for free. Mirror photos instantly. No sign-up required. Supports JPG, PNG, WebP.',
      keywords: ['flip image online free', 'mirror image online', 'flip photo', 'horizontal flip image'],
    },
    relatedToolSlugs: ['image-rotate', 'image-crop', 'image-resize', 'image-compress'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'image-grayscale',
    slug: 'image-grayscale',
    title: 'Grayscale Converter',
    shortTitle: 'Grayscale Image',
    description:
      'Convert color images to black and white or grayscale. Control the conversion intensity. Perfect for artistic effects and print preparation.',
    shortDescription: 'Convert color images to black and white.',
    category: 'image',
    subcategory: 'effects',
    icon: Contrast,
    keywords: [
      'grayscale image',
      'black and white photo',
      'convert to grayscale',
      'desaturate image',
      'black white image converter',
      'b&w photo',
    ],
    tags: ['grayscale', 'black white', 'effects', 'image'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'server',
    supportedInputFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    supportedOutputFormats: ['.jpg', '.png', '.webp'],
    maxFileSizeMb: 50,
    seo: {
      title: 'Convert Image to Grayscale — Free Black & White Converter',
      description:
        'Convert color photos to black and white or grayscale online for free. Instant conversion, no quality loss. Supports JPG and PNG.',
      keywords: [
        'convert image to grayscale free',
        'black white photo converter',
        'desaturate image online',
        'grayscale filter online',
      ],
    },
    relatedToolSlugs: ['image-compress', 'image-convert', 'image-brightness', 'image-rotate'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'image-brightness',
    slug: 'image-brightness',
    title: 'Image Brightness & Contrast',
    shortTitle: 'Brightness & Contrast',
    description:
      'Adjust brightness, contrast, saturation, and sharpness of images online. Fine-tune photos with real-time preview before downloading.',
    shortDescription: 'Adjust brightness, contrast, and saturation of images.',
    category: 'image',
    subcategory: 'effects',
    icon: SunDim,
    keywords: [
      'adjust image brightness',
      'image contrast adjuster',
      'brighten image',
      'image saturation',
      'photo brightness editor',
      'lighten image',
    ],
    tags: ['brightness', 'contrast', 'saturation', 'image', 'adjust'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'server',
    supportedInputFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    supportedOutputFormats: ['.jpg', '.png', '.webp'],
    maxFileSizeMb: 50,
    seo: {
      title: 'Adjust Image Brightness & Contrast Online — Free Tool',
      description:
        'Adjust brightness, contrast, and saturation of images online for free. Real-time preview. Supports JPG and PNG. No sign-up required.',
      keywords: [
        'adjust image brightness online',
        'image brightness contrast tool',
        'brighten photo online free',
        'image color adjuster',
      ],
    },
    relatedToolSlugs: ['image-compress', 'image-grayscale', 'image-convert', 'image-resize'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'image-to-base64',
    slug: 'image-to-base64',
    title: 'Image to Base64',
    shortTitle: 'Image to Base64',
    description:
      'Convert images to Base64-encoded strings for embedding in HTML, CSS, or JSON. Also decode Base64 strings back to images. Runs entirely in your browser.',
    shortDescription: 'Convert images to Base64 strings and back.',
    category: 'image',
    subcategory: 'conversion',
    icon: FileCode,
    keywords: [
      'image to base64',
      'base64 encode image',
      'base64 image converter',
      'encode image base64',
      'base64 decode image',
      'image data uri',
    ],
    tags: ['base64', 'encode', 'convert', 'data uri', 'image'],
    difficulty: 'intermediate',
    status: 'active',
    processingMode: 'browser',
    isNew: true,
    supportedInputFormats: ['.jpg', '.jpeg', '.png', '.webp', '.gif', '.svg'],
    seo: {
      title: 'Image to Base64 Converter — Encode Images Online Free',
      description:
        'Convert images to Base64 encoded strings online. Embed images in HTML or CSS as data URIs. Also decode Base64 back to image. Free and instant.',
      keywords: [
        'image to base64 converter free',
        'encode image to base64',
        'base64 image online',
        'image data uri generator',
      ],
    },
    relatedToolSlugs: ['base64-encoder', 'image-compress', 'image-convert', 'image-resize'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
]

