import {
  Copy,
  FileImage,
  FileOutput,
  Files,
  FileSpreadsheet,
  FileText,
  Lock,
  Minimize2,
  Pencil,
  RotateCw,
  Scissors,
  Shield,
  Stamp,
  Unlock,
} from 'lucide-react'

import type { ToolMeta } from '../types'

/**
 * PDF Tools Registry
 * ══════════════════════════════════════════════════════════════════════════
 * All tools here require server-side processing (pdf-lib, pdfjs, etc.)
 * They will be implemented in Sprint 9 once the backend is ready.
 * They are registered now so that:
 *  - SEO pages and "coming soon" tool pages can be generated
 *  - Search, category pages, and the sitemap are complete from day one
 *  - Related tool links work across all tools immediately
 * ══════════════════════════════════════════════════════════════════════════
 */

export const pdfTools: ToolMeta[] = [
  {
    id: 'pdf-merge',
    slug: 'pdf-merge',
    title: 'Merge PDF',
    shortTitle: 'Merge PDF',
    description:
      'Combine multiple PDF files into a single document in seconds. Drag, drop, reorder, and merge — all in your browser. No registration required.',
    shortDescription: 'Combine multiple PDF files into one document.',
    category: 'pdf',
    subcategory: 'organization',
    icon: Files,
    keywords: [
      'merge pdf',
      'combine pdf',
      'join pdf',
      'pdf merger',
      'combine pdf files',
      'merge pdf online',
      'pdf joiner',
    ],
    tags: ['merge', 'combine', 'pdf'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    isFeatured: true,
    supportedInputFormats: ['.pdf'],
    supportedOutputFormats: ['.pdf'],
    maxFileSizeMb: 100,
    seo: {
      title: 'Merge PDF Files Online — Free PDF Merger',
      description:
        'Merge multiple PDF files into one document online. Free, fast, and secure. No sign-up required. Drag and drop your files to combine them instantly.',
      keywords: ['merge pdf online', 'combine pdf files free', 'pdf merger tool', 'join pdf online'],
    },
    relatedToolSlugs: ['pdf-split', 'pdf-compress', 'pdf-rotate', 'pdf-to-word'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'pdf-split',
    slug: 'pdf-split',
    title: 'Split PDF',
    shortTitle: 'Split PDF',
    description:
      'Split a PDF into multiple files by page ranges, individual pages, or file size. Extract exactly the pages you need with full control.',
    shortDescription: 'Split a PDF into multiple files or extract pages.',
    category: 'pdf',
    subcategory: 'organization',
    icon: Scissors,
    keywords: [
      'split pdf',
      'divide pdf',
      'extract pdf pages',
      'pdf splitter',
      'cut pdf',
      'separate pdf pages',
    ],
    tags: ['split', 'extract', 'pdf', 'pages'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    supportedInputFormats: ['.pdf'],
    supportedOutputFormats: ['.pdf'],
    maxFileSizeMb: 100,
    seo: {
      title: 'Split PDF Online — Extract Pages from PDF Free',
      description:
        'Split a large PDF into smaller files or extract specific pages online. Free, no watermarks, no registration. Works on any device.',
      keywords: ['split pdf online', 'extract pages from pdf', 'pdf splitter free', 'cut pdf pages'],
    },
    relatedToolSlugs: ['pdf-merge', 'pdf-compress', 'pdf-page-extractor', 'pdf-rotate'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'pdf-compress',
    slug: 'pdf-compress',
    title: 'Compress PDF',
    shortTitle: 'Compress PDF',
    description:
      'Reduce PDF file size without losing quality. Intelligent compression removes redundant data while preserving text sharpness and image quality.',
    shortDescription: 'Reduce PDF file size without losing quality.',
    category: 'pdf',
    subcategory: 'optimization',
    icon: Minimize2,
    keywords: [
      'compress pdf',
      'reduce pdf size',
      'pdf compressor',
      'shrink pdf',
      'pdf size reducer',
      'optimize pdf',
      'pdf file size',
    ],
    tags: ['compress', 'optimize', 'pdf', 'size'],
    difficulty: 'beginner',
    status: 'coming-soon',
    processingMode: 'server',
    isPopular: true,
    isFeatured: true,
    supportedInputFormats: ['.pdf'],
    supportedOutputFormats: ['.pdf'],
    maxFileSizeMb: 100,
    seo: {
      title: 'Compress PDF Online — Reduce PDF File Size Free',
      description:
        'Compress PDF files and reduce their size online for free. No quality loss. Perfect for email attachments, uploads, and storage.',
      keywords: [
        'compress pdf online',
        'reduce pdf file size',
        'pdf compressor free',
        'shrink pdf size',
      ],
    },
    relatedToolSlugs: ['pdf-merge', 'pdf-split', 'pdf-to-image', 'image-compress'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'pdf-rotate',
    slug: 'pdf-rotate',
    title: 'Rotate PDF',
    shortTitle: 'Rotate PDF',
    description:
      'Rotate PDF pages by 90°, 180°, or 270°. Rotate all pages at once or select individual pages. Changes are permanent and saved to the output file.',
    shortDescription: 'Rotate PDF pages by any angle.',
    category: 'pdf',
    subcategory: 'editing',
    icon: RotateCw,
    keywords: ['rotate pdf', 'pdf rotate pages', 'flip pdf', 'turn pdf pages', 'pdf orientation'],
    tags: ['rotate', 'orientation', 'pdf', 'pages'],
    difficulty: 'beginner',
    status: 'coming-soon',
    processingMode: 'server',
    supportedInputFormats: ['.pdf'],
    supportedOutputFormats: ['.pdf'],
    maxFileSizeMb: 100,
    seo: {
      title: 'Rotate PDF Pages Online — Free PDF Rotation Tool',
      description:
        'Rotate PDF pages online for free. Rotate all pages or specific pages by 90, 180, or 270 degrees. No sign-up, no watermarks.',
      keywords: ['rotate pdf online', 'rotate pdf pages', 'pdf rotation tool free'],
    },
    relatedToolSlugs: ['pdf-merge', 'pdf-split', 'pdf-compress', 'pdf-page-extractor'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'pdf-protect',
    slug: 'pdf-protect',
    title: 'Protect PDF',
    shortTitle: 'Protect PDF',
    description:
      'Add password protection to your PDF files. Set owner and user passwords. Restrict printing, copying, and editing with encryption.',
    shortDescription: 'Password-protect and encrypt PDF files.',
    category: 'pdf',
    subcategory: 'security',
    icon: Lock,
    keywords: [
      'protect pdf',
      'password protect pdf',
      'encrypt pdf',
      'lock pdf',
      'secure pdf',
      'pdf password',
    ],
    tags: ['protect', 'password', 'security', 'pdf'],
    difficulty: 'beginner',
    status: 'coming-soon',
    processingMode: 'server',
    supportedInputFormats: ['.pdf'],
    supportedOutputFormats: ['.pdf'],
    maxFileSizeMb: 100,
    seo: {
      title: 'Protect PDF with Password — Free PDF Encryption Tool',
      description:
        'Add password protection to PDF files online. Encrypt your PDF with AES-256. Restrict printing and copying. Free, fast, and secure.',
      keywords: ['protect pdf with password', 'encrypt pdf online', 'lock pdf free', 'secure pdf'],
    },
    relatedToolSlugs: ['pdf-unlock', 'pdf-compress', 'pdf-watermark'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'pdf-unlock',
    slug: 'pdf-unlock',
    title: 'Unlock PDF',
    shortTitle: 'Unlock PDF',
    description:
      'Remove password protection from PDF files you have permission to access. Unlock editing, printing, and copying restrictions instantly.',
    shortDescription: 'Remove password protection from PDF files.',
    category: 'pdf',
    subcategory: 'security',
    icon: Unlock,
    keywords: [
      'unlock pdf',
      'remove pdf password',
      'decrypt pdf',
      'pdf password remover',
      'unlock pdf restrictions',
    ],
    tags: ['unlock', 'password', 'security', 'pdf'],
    difficulty: 'beginner',
    status: 'coming-soon',
    processingMode: 'server',
    supportedInputFormats: ['.pdf'],
    supportedOutputFormats: ['.pdf'],
    maxFileSizeMb: 100,
    seo: {
      title: 'Unlock PDF — Remove PDF Password Online Free',
      description:
        'Remove password protection from PDF files online. Unlock editing and printing restrictions instantly. Free tool, no software required.',
      keywords: [
        'unlock pdf online',
        'remove pdf password free',
        'decrypt pdf',
        'unlock pdf restrictions',
      ],
    },
    relatedToolSlugs: ['pdf-protect', 'pdf-compress', 'pdf-merge'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'pdf-watermark',
    slug: 'pdf-watermark',
    title: 'Watermark PDF',
    shortTitle: 'Watermark PDF',
    description:
      'Add text or image watermarks to your PDF files. Customize the position, opacity, font, size, and angle. Protect your documents with branding.',
    shortDescription: 'Add text or image watermarks to PDF files.',
    category: 'pdf',
    subcategory: 'editing',
    icon: Stamp,
    keywords: [
      'watermark pdf',
      'add watermark to pdf',
      'pdf watermark tool',
      'stamp pdf',
      'text watermark pdf',
    ],
    tags: ['watermark', 'branding', 'editing', 'pdf'],
    difficulty: 'intermediate',
    status: 'coming-soon',
    processingMode: 'server',
    supportedInputFormats: ['.pdf'],
    supportedOutputFormats: ['.pdf'],
    maxFileSizeMb: 100,
    seo: {
      title: 'Add Watermark to PDF Online — Free PDF Watermark Tool',
      description:
        'Add custom text or image watermarks to PDF files online. Free tool. Set opacity, position, and angle. No registration required.',
      keywords: ['add watermark to pdf', 'pdf watermark online free', 'stamp pdf online'],
    },
    relatedToolSlugs: ['pdf-protect', 'pdf-merge', 'pdf-compress', 'image-watermark'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'pdf-to-word',
    slug: 'pdf-to-word',
    title: 'PDF to Word Converter',
    shortTitle: 'PDF to Word',
    description:
      'Convert PDF files to editable Microsoft Word documents (.docx). Preserves formatting, tables, images, and text layout with high accuracy.',
    shortDescription: 'Convert PDF to editable Word documents instantly.',
    category: 'pdf',
    subcategory: 'conversion',
    icon: FileText,
    keywords: [
      'pdf to word',
      'convert pdf to word',
      'pdf to docx',
      'pdf word converter',
      'pdf to editable word',
    ],
    tags: ['convert', 'pdf', 'word', 'docx'],
    difficulty: 'beginner',
    status: 'coming-soon',
    processingMode: 'server',
    isPopular: true,
    isFeatured: true,
    supportedInputFormats: ['.pdf'],
    supportedOutputFormats: ['.docx'],
    maxFileSizeMb: 50,
    seo: {
      title: 'PDF to Word Converter — Free Online PDF to DOCX',
      description:
        'Convert PDF to Word documents online for free. High accuracy OCR. Preserves tables, images, and formatting. Download as .docx instantly.',
      keywords: [
        'pdf to word converter free',
        'convert pdf to docx online',
        'pdf to editable word',
        'pdf word converter',
      ],
    },
    relatedToolSlugs: ['word-to-pdf', 'pdf-compress', 'pdf-to-excel', 'pdf-merge'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'word-to-pdf',
    slug: 'word-to-pdf',
    title: 'Word to PDF Converter',
    shortTitle: 'Word to PDF',
    description:
      'Convert Microsoft Word documents (.doc, .docx) to PDF format. Preserves all fonts, images, and formatting exactly as intended.',
    shortDescription: 'Convert Word documents to PDF format.',
    category: 'pdf',
    subcategory: 'conversion',
    icon: FileOutput,
    keywords: [
      'word to pdf',
      'convert word to pdf',
      'docx to pdf',
      'doc to pdf',
      'word pdf converter',
    ],
    tags: ['convert', 'word', 'pdf', 'docx'],
    difficulty: 'beginner',
    status: 'coming-soon',
    processingMode: 'server',
    isPopular: true,
    supportedInputFormats: ['.doc', '.docx'],
    supportedOutputFormats: ['.pdf'],
    maxFileSizeMb: 50,
    seo: {
      title: 'Word to PDF Converter — Free Online DOCX to PDF',
      description:
        'Convert Word documents to PDF online for free. Upload .doc or .docx and download a perfect PDF instantly. No sign-up required.',
      keywords: [
        'word to pdf converter free',
        'convert docx to pdf online',
        'doc to pdf',
        'word pdf converter',
      ],
    },
    relatedToolSlugs: ['pdf-to-word', 'pdf-compress', 'pdf-merge', 'pdf-protect'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'pdf-to-image',
    slug: 'pdf-to-image',
    title: 'PDF to Image Converter',
    shortTitle: 'PDF to Image',
    description:
      'Convert PDF pages to high-quality JPG, PNG, or WebP images. Convert all pages or select specific ones. Control output resolution and quality.',
    shortDescription: 'Convert PDF pages to JPG, PNG, or WebP images.',
    category: 'pdf',
    subcategory: 'conversion',
    icon: FileImage,
    keywords: [
      'pdf to image',
      'pdf to jpg',
      'pdf to png',
      'convert pdf to image',
      'pdf page to image',
      'pdf screenshot',
    ],
    tags: ['convert', 'pdf', 'image', 'jpg', 'png'],
    difficulty: 'beginner',
    status: 'coming-soon',
    processingMode: 'server',
    isPopular: true,
    supportedInputFormats: ['.pdf'],
    supportedOutputFormats: ['.jpg', '.png', '.webp'],
    maxFileSizeMb: 50,
    seo: {
      title: 'PDF to Image Converter — Convert PDF to JPG or PNG Free',
      description:
        'Convert PDF pages to high-quality images online. Export as JPG, PNG, or WebP. Select specific pages. Free, no watermarks.',
      keywords: [
        'pdf to jpg converter free',
        'pdf to png online',
        'convert pdf to image',
        'pdf page image export',
      ],
    },
    relatedToolSlugs: ['pdf-compress', 'pdf-to-word', 'image-compress', 'image-convert'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'pdf-to-excel',
    slug: 'pdf-to-excel',
    title: 'PDF to Excel Converter',
    shortTitle: 'PDF to Excel',
    description:
      'Extract tables and data from PDF files and convert them to editable Microsoft Excel spreadsheets. Preserves rows, columns, and cell structure.',
    shortDescription: 'Convert PDF tables to editable Excel spreadsheets.',
    category: 'pdf',
    subcategory: 'conversion',
    icon: FileSpreadsheet,
    keywords: [
      'pdf to excel',
      'pdf to xlsx',
      'convert pdf to spreadsheet',
      'extract table from pdf',
      'pdf table extractor',
    ],
    tags: ['convert', 'pdf', 'excel', 'xlsx', 'spreadsheet'],
    difficulty: 'intermediate',
    status: 'coming-soon',
    processingMode: 'server',
    supportedInputFormats: ['.pdf'],
    supportedOutputFormats: ['.xlsx'],
    maxFileSizeMb: 50,
    seo: {
      title: 'PDF to Excel Converter — Extract Tables from PDF Free',
      description:
        'Convert PDF files with tables to Excel spreadsheets online. Free PDF to XLSX converter. Accurate table extraction with row and column structure.',
      keywords: [
        'pdf to excel converter free',
        'pdf to xlsx online',
        'extract table from pdf',
        'pdf spreadsheet converter',
      ],
    },
    relatedToolSlugs: ['pdf-to-word', 'word-to-pdf', 'pdf-compress', 'pdf-merge'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'pdf-page-extractor',
    slug: 'pdf-page-extractor',
    title: 'PDF Page Extractor',
    shortTitle: 'Extract PDF Pages',
    description:
      'Extract specific pages from a PDF file and save them as a new document. Select individual pages or ranges. Perfect for sharing selected content.',
    shortDescription: 'Extract specific pages from a PDF file.',
    category: 'pdf',
    subcategory: 'editing',
    icon: Copy,
    keywords: [
      'extract pdf pages',
      'pdf page extractor',
      'select pdf pages',
      'pdf page picker',
      'extract pages from pdf',
    ],
    tags: ['extract', 'pages', 'pdf', 'select'],
    difficulty: 'beginner',
    status: 'coming-soon',
    processingMode: 'server',
    supportedInputFormats: ['.pdf'],
    supportedOutputFormats: ['.pdf'],
    maxFileSizeMb: 100,
    seo: {
      title: 'PDF Page Extractor — Extract Pages from PDF Free Online',
      description:
        'Extract specific pages from a PDF file online. Select page ranges or individual pages. Download as a new PDF. Free, fast, no sign-up.',
      keywords: [
        'extract pages from pdf free',
        'pdf page picker online',
        'select pdf pages',
        'pdf extractor',
      ],
    },
    relatedToolSlugs: ['pdf-split', 'pdf-merge', 'pdf-rotate', 'pdf-compress'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'pdf-metadata-editor',
    slug: 'pdf-metadata-editor',
    title: 'PDF Metadata Editor',
    shortTitle: 'PDF Metadata',
    description:
      'View and edit PDF document metadata including title, author, subject, keywords, and creation date. Clean up document properties before sharing.',
    shortDescription: 'View and edit PDF title, author, and document properties.',
    category: 'pdf',
    subcategory: 'editing',
    icon: Pencil,
    keywords: [
      'pdf metadata editor',
      'edit pdf properties',
      'pdf document info',
      'pdf author editor',
      'pdf title editor',
    ],
    tags: ['metadata', 'properties', 'pdf', 'edit'],
    difficulty: 'intermediate',
    status: 'coming-soon',
    processingMode: 'server',
    supportedInputFormats: ['.pdf'],
    supportedOutputFormats: ['.pdf'],
    maxFileSizeMb: 100,
    seo: {
      title: 'PDF Metadata Editor — Edit PDF Properties Online Free',
      description:
        'Edit PDF metadata online. Change the title, author, subject, and keywords of any PDF file. Free tool, no software required.',
      keywords: [
        'pdf metadata editor online',
        'edit pdf document properties',
        'pdf info editor',
        'change pdf author',
      ],
    },
    relatedToolSlugs: ['pdf-protect', 'pdf-watermark', 'pdf-compress', 'pdf-merge'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'pdf-ocr',
    slug: 'pdf-ocr',
    title: 'PDF OCR — Text Extractor',
    shortTitle: 'PDF OCR',
    description:
      'Extract text from scanned PDF files and images using Optical Character Recognition. Convert image-based PDFs into searchable, selectable text.',
    shortDescription: 'Extract text from scanned PDFs using OCR.',
    category: 'pdf',
    subcategory: 'extraction',
    icon: Shield,
    keywords: [
      'pdf ocr',
      'ocr pdf',
      'extract text from pdf',
      'scanned pdf to text',
      'pdf text extractor',
      'searchable pdf',
    ],
    tags: ['ocr', 'text', 'extract', 'scan', 'pdf'],
    difficulty: 'intermediate',
    status: 'coming-soon',
    processingMode: 'server',
    isPremium: true,
    supportedInputFormats: ['.pdf', '.png', '.jpg', '.jpeg', '.tiff'],
    supportedOutputFormats: ['.pdf', '.txt'],
    maxFileSizeMb: 50,
    seo: {
      title: 'PDF OCR — Extract Text from Scanned PDF Online',
      description:
        'Convert scanned PDFs to searchable text with OCR technology. Extract text from image-based PDF files online. High accuracy, 100+ languages.',
      keywords: ['pdf ocr online', 'extract text from scanned pdf', 'ocr pdf free', 'pdf text recognition'],
    },
    relatedToolSlugs: ['pdf-to-word', 'pdf-to-image', 'pdf-compress', 'pdf-metadata-editor'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
]

