import {
  BarChart2,
  BookOpen,
  Bot,
  Globe,
  Link,
  Map,
  Tag,
} from 'lucide-react'

import type { ToolMeta } from '../types'

/**
 * SEO Tools Registry
 * ══════════════════════════════════════════════════════════════════════════
 * All tools here run in the browser — they generate SEO-related code/content.
 * No backend required.
 * ══════════════════════════════════════════════════════════════════════════
 */

export const seoTools: ToolMeta[] = [
  {
    id: 'meta-generator',
    slug: 'meta-generator',
    title: 'Meta Tag Generator',
    shortTitle: 'Meta Generator',
    description:
      'Generate HTML meta tags for SEO, Open Graph, and Twitter Card. Preview how your page will appear in Google search results and social media shares.',
    shortDescription: 'Generate SEO, Open Graph, and Twitter Card meta tags.',
    category: 'seo',
    subcategory: 'generation',
    icon: Tag,
    keywords: [
      'meta tag generator',
      'seo meta tags',
      'open graph generator',
      'twitter card generator',
      'html meta tags',
      'seo tags generator',
    ],
    tags: ['meta tags', 'seo', 'open graph', 'twitter card'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isFeatured: true,
    seo: {
      title: 'Meta Tag Generator — Generate SEO & OG Tags Free',
      description:
        'Generate HTML meta tags for SEO, Open Graph, and Twitter Cards. Preview Google SERP snippet and social media previews. Free, instant.',
      keywords: [
        'meta tag generator free',
        'seo meta tags generator',
        'open graph tag generator',
        'twitter card generator',
        'html meta generator',
      ],
    },
    relatedToolSlugs: ['og-generator', 'robots-generator', 'keyword-density', 'sitemap-generator'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'og-generator',
    slug: 'og-generator',
    title: 'Open Graph Generator',
    shortTitle: 'OG Generator',
    description:
      'Generate Open Graph meta tags for Facebook, LinkedIn, and other social platforms. Preview how your link will appear when shared on social media.',
    shortDescription: 'Generate Open Graph tags for social media sharing.',
    category: 'seo',
    subcategory: 'generation',
    icon: Globe,
    keywords: [
      'open graph generator',
      'og meta tags',
      'facebook meta tags',
      'social media preview',
      'og tags generator',
      'opengraph generator',
    ],
    tags: ['open graph', 'social media', 'facebook', 'seo'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Open Graph Generator — Generate OG Meta Tags Free',
      description:
        'Generate Open Graph meta tags for Facebook, LinkedIn, and Twitter. Preview your social media link card before publishing. Free, instant.',
      keywords: [
        'open graph generator free',
        'og meta tag generator',
        'facebook meta tags generator',
        'social media tag generator',
      ],
    },
    relatedToolSlugs: ['meta-generator', 'robots-generator', 'sitemap-generator', 'keyword-density'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'robots-generator',
    slug: 'robots-generator',
    title: 'Robots.txt Generator',
    shortTitle: 'Robots Generator',
    description:
      'Generate a robots.txt file for your website. Configure rules for specific user agents, disallow directories, and set your sitemap URL. Preview instantly.',
    shortDescription: 'Generate robots.txt files for SEO crawl control.',
    category: 'seo',
    subcategory: 'generation',
    icon: Bot,
    keywords: [
      'robots.txt generator',
      'robots txt generator',
      'generate robots.txt',
      'robots file generator',
      'disallow robots',
      'seo robots file',
    ],
    tags: ['robots.txt', 'crawl', 'seo', 'google'],
    difficulty: 'intermediate',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Robots.txt Generator — Create Robots File Online Free',
      description:
        'Generate a robots.txt file for your website. Set crawl rules for search engines. Configure disallow rules and sitemap URL. Free, instant.',
      keywords: [
        'robots.txt generator free',
        'generate robots txt online',
        'create robots.txt file',
        'seo robots generator',
      ],
    },
    relatedToolSlugs: ['sitemap-generator', 'meta-generator', 'og-generator', 'keyword-density'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'sitemap-generator',
    slug: 'sitemap-generator',
    title: 'XML Sitemap Generator',
    shortTitle: 'Sitemap Generator',
    description:
      'Generate XML sitemaps for your website to help search engines discover all your pages. Set priorities, change frequencies, and last modified dates.',
    shortDescription: 'Generate XML sitemaps for search engine indexing.',
    category: 'seo',
    subcategory: 'generation',
    icon: Map,
    keywords: [
      'sitemap generator',
      'xml sitemap generator',
      'generate sitemap',
      'website sitemap creator',
      'seo sitemap tool',
    ],
    tags: ['sitemap', 'xml', 'seo', 'google'],
    difficulty: 'intermediate',
    status: 'active',
    processingMode: 'server',
    seo: {
      title: 'XML Sitemap Generator — Create Sitemap Online Free',
      description:
        'Generate XML sitemaps for your website online. Help search engines discover all your pages. Set priorities and change frequencies. Free tool.',
      keywords: [
        'sitemap generator free',
        'xml sitemap creator',
        'generate website sitemap',
        'seo sitemap generator',
      ],
    },
    relatedToolSlugs: ['robots-generator', 'meta-generator', 'og-generator', 'keyword-density'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'keyword-density',
    slug: 'keyword-density',
    title: 'Keyword Density Checker',
    shortTitle: 'Keyword Density',
    description:
      'Analyze keyword density in your content. Find the most frequently used words and phrases. Identify over-optimized or under-optimized keywords.',
    shortDescription: 'Analyze keyword density and frequency in text content.',
    category: 'seo',
    subcategory: 'analysis',
    icon: BarChart2,
    keywords: [
      'keyword density checker',
      'keyword density analyzer',
      'keyword frequency',
      'seo keyword analysis',
      'content keyword analysis',
    ],
    tags: ['keyword', 'density', 'seo', 'analysis'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Keyword Density Checker — Analyze Keywords in Text Free',
      description:
        'Check keyword density in your content online. Analyze word frequency and find over-optimized terms. Free SEO tool, no sign-up required.',
      keywords: [
        'keyword density checker free',
        'keyword frequency analyzer',
        'seo keyword density tool',
        'content keyword checker',
      ],
    },
    relatedToolSlugs: ['meta-generator', 'robots-generator', 'readability-checker', 'word-counter'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'readability-checker',
    slug: 'readability-checker',
    title: 'Readability Checker',
    shortTitle: 'Readability',
    description:
      'Analyze the readability of your content using Flesch Reading Ease, Flesch-Kincaid Grade Level, and other readability scores. Get improvement suggestions.',
    shortDescription: 'Analyze content readability with Flesch-Kincaid scores.',
    category: 'seo',
    subcategory: 'analysis',
    icon: BookOpen,
    keywords: [
      'readability checker',
      'readability score',
      'flesch kincaid',
      'flesch reading ease',
      'content readability',
      'reading level checker',
    ],
    tags: ['readability', 'flesch', 'content', 'seo'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Readability Checker — Flesch-Kincaid Score Online Free',
      description:
        'Check your content readability online. Get Flesch-Kincaid grade level and reading ease scores. Improve your writing for better SEO. Free, instant.',
      keywords: [
        'readability checker free',
        'flesch kincaid calculator',
        'content readability score',
        'reading level checker online',
      ],
    },
    relatedToolSlugs: ['keyword-density', 'word-counter', 'meta-generator', 'text-compare'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  /* ── Sprint 7: New SEO Tools ─────────────────────────────────────── */
  {
    id: 'utm-builder',
    slug: 'utm-builder',
    title: 'UTM Parameter Builder',
    shortTitle: 'UTM Builder',
    description:
      'Build UTM tracking URLs for Google Analytics campaigns. Add source, medium, campaign, term, and content parameters. Copy the full UTM URL instantly.',
    shortDescription: 'Build UTM tracking URLs for Google Analytics campaigns.',
    category: 'seo',
    subcategory: 'analytics',
    icon: Link,
    keywords: ['utm builder', 'utm parameter generator', 'google analytics utm', 'campaign url builder', 'utm tracking url', 'utm link generator'],
    tags: ['utm', 'analytics', 'tracking', 'seo', 'google analytics'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'UTM Parameter Builder — Build UTM Tracking URLs Free',
      description: 'Build UTM tracking URLs for Google Analytics. Add UTM source, medium, campaign parameters. Copy URL instantly. Free, no sign-up.',
      keywords: ['utm builder online free', 'utm parameter generator', 'google analytics utm builder', 'campaign url builder free'],
    },
    relatedToolSlugs: ['meta-generator', 'og-generator', 'sitemap-generator', 'schema-markup-generator'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'schema-markup-generator',
    slug: 'schema-markup-generator',
    title: 'Schema Markup Generator',
    shortTitle: 'Schema Generator',
    description:
      'Generate JSON-LD structured data markup for SEO. Supports Website, Article, Organization, FAQPage, BreadcrumbList, and LocalBusiness schema types.',
    shortDescription: 'Generate JSON-LD structured data (Schema.org) for SEO.',
    category: 'seo',
    subcategory: 'structured-data',
    icon: Tag,
    keywords: ['schema markup generator', 'json-ld generator', 'structured data generator', 'schema.org generator', 'seo schema markup', 'rich snippet generator'],
    tags: ['schema', 'json-ld', 'structured data', 'seo', 'rich snippets'],
    difficulty: 'intermediate',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Schema Markup Generator — JSON-LD Structured Data Free',
      description: 'Generate JSON-LD schema markup for SEO. Website, Article, Organization, FAQ, LocalBusiness schemas. Free, instant.',
      keywords: ['schema markup generator free', 'json-ld generator', 'structured data generator online', 'schema.org markup tool'],
    },
    relatedToolSlugs: ['meta-generator', 'og-generator', 'utm-builder', 'sitemap-generator'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
]

