import {
  Activity,
  AlignJustify,
  AlignLeft,
  ArrowUpDown,
  Binary,
  CaseSensitive,
  FileText,
  GitCompare,
  Hash,
  ListFilter,
  Radio,
  Replace,
  RotateCcw,
  Shield,
  SquareAsterisk,
  Type,
} from 'lucide-react'

import type { ToolMeta } from '../types'

/**
 * Text Tools Registry
 * ══════════════════════════════════════════════════════════════════════════
 * All tools here run entirely in the browser (processingMode: 'browser').
 * No file uploads required — pure text processing.
 * Implementation target: Sprint 4.
 * ══════════════════════════════════════════════════════════════════════════
 */

export const textTools: ToolMeta[] = [
  {
    id: 'word-counter',
    slug: 'word-counter',
    title: 'Word Counter',
    shortTitle: 'Word Counter',
    description:
      'Count words, characters, sentences, paragraphs, and reading time in real time. Ideal for essays, blog posts, social media character limits, and SEO content.',
    shortDescription: 'Count words, characters, sentences, and reading time.',
    category: 'text',
    subcategory: 'analysis',
    icon: AlignLeft,
    keywords: [
      'word counter',
      'word count',
      'character counter',
      'count words online',
      'word count checker',
      'word counter online',
      'text length counter',
    ],
    tags: ['word count', 'characters', 'reading time', 'text'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    isFeatured: true,
    seo: {
      title: 'Word Counter — Count Words, Characters & Reading Time Free',
      description:
        'Count words, characters, sentences, paragraphs, and reading time online for free. Real-time word counter. No sign-up required.',
      keywords: [
        'word counter online free',
        'word count tool',
        'character count online',
        'count words online',
        'reading time calculator',
      ],
    },
    relatedToolSlugs: ['character-counter', 'case-converter', 'remove-duplicate-lines', 'lorem-ipsum'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'character-counter',
    slug: 'character-counter',
    title: 'Character Counter',
    shortTitle: 'Character Counter',
    description:
      'Count characters with or without spaces. Track limits for Twitter, Instagram, SMS, and other platforms. See per-platform remaining character counts.',
    shortDescription: 'Count characters and track social media limits.',
    category: 'text',
    subcategory: 'analysis',
    icon: Type,
    keywords: [
      'character counter',
      'character count',
      'letter counter',
      'text length',
      'twitter character limit',
      'instagram character count',
      'sms character count',
    ],
    tags: ['characters', 'counter', 'social media', 'text'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    seo: {
      title: 'Character Counter — Count Characters Online Free',
      description:
        'Count characters with and without spaces online. Track Twitter, Instagram, SMS, and YouTube character limits in real time. Free, instant.',
      keywords: [
        'character counter online free',
        'count characters online',
        'twitter character counter',
        'sms character limit tool',
        'letter counter',
      ],
    },
    relatedToolSlugs: ['word-counter', 'case-converter', 'remove-whitespace', 'lorem-ipsum'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'case-converter',
    slug: 'case-converter',
    title: 'Case Converter',
    shortTitle: 'Case Converter',
    description:
      'Convert text between UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, and kebab-case instantly.',
    shortDescription: 'Convert text between uppercase, lowercase, title case, and more.',
    category: 'text',
    subcategory: 'transformation',
    icon: CaseSensitive,
    keywords: [
      'case converter',
      'text case converter',
      'uppercase converter',
      'lowercase converter',
      'title case converter',
      'camelcase converter',
      'snake case',
      'kebab case',
    ],
    tags: ['case', 'uppercase', 'lowercase', 'camelCase', 'text'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    isPopular: true,
    isFeatured: true,
    seo: {
      title: 'Case Converter — UPPERCASE, lowercase, Title Case Online Free',
      description:
        'Convert text to UPPERCASE, lowercase, Title Case, camelCase, PascalCase, snake_case, and kebab-case online. Free, instant, no sign-up.',
      keywords: [
        'case converter online free',
        'uppercase converter',
        'text case changer',
        'camelcase converter',
        'snake case converter',
      ],
    },
    relatedToolSlugs: ['word-counter', 'character-counter', 'text-to-slug', 'remove-whitespace'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'remove-duplicate-lines',
    slug: 'remove-duplicate-lines',
    title: 'Remove Duplicate Lines',
    shortTitle: 'Remove Duplicates',
    description:
      'Remove duplicate lines from text instantly. Option to ignore case, sort lines after removal, and count how many duplicates were removed.',
    shortDescription: 'Remove duplicate lines from text.',
    category: 'text',
    subcategory: 'cleaning',
    icon: ListFilter,
    keywords: [
      'remove duplicate lines',
      'delete duplicate lines',
      'remove duplicates text',
      'unique lines',
      'deduplicate text',
      'filter duplicate lines',
    ],
    tags: ['duplicates', 'clean', 'lines', 'text'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Remove Duplicate Lines — Delete Duplicate Text Lines Free',
      description:
        'Remove duplicate lines from text online. Filter out repeating lines, ignore case, and sort results. Free, instant, no sign-up required.',
      keywords: [
        'remove duplicate lines online free',
        'delete duplicate text lines',
        'deduplicate text online',
        'unique lines tool',
      ],
    },
    relatedToolSlugs: ['text-sorter', 'remove-whitespace', 'word-counter', 'text-compare'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'text-compare',
    slug: 'text-compare',
    title: 'Text Compare',
    shortTitle: 'Text Compare',
    description:
      'Compare two pieces of text and highlight the differences line by line. Useful for spotting changes in documents, code, and content revisions.',
    shortDescription: 'Compare two texts and highlight the differences.',
    category: 'text',
    subcategory: 'analysis',
    icon: GitCompare,
    keywords: [
      'text compare',
      'text diff',
      'compare text online',
      'text difference checker',
      'diff tool',
      'compare two texts',
      'text comparison',
    ],
    tags: ['compare', 'diff', 'difference', 'text'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Text Compare — Compare Two Texts Online Free',
      description:
        'Compare two texts and highlight differences online. Find changes line by line. Free diff tool. No sign-up required.',
      keywords: [
        'text compare online free',
        'text diff tool',
        'compare two texts',
        'find text differences',
        'online diff checker',
      ],
    },
    relatedToolSlugs: ['remove-duplicate-lines', 'word-counter', 'text-sorter', 'markdown-preview'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'text-reverser',
    slug: 'text-reverser',
    title: 'Text Reverser',
    shortTitle: 'Reverse Text',
    description:
      'Reverse text character by character or word by word. Flip a sentence, reverse a paragraph, or mirror any piece of text instantly.',
    shortDescription: 'Reverse text character by character or word by word.',
    category: 'text',
    subcategory: 'transformation',
    icon: RotateCcw,
    keywords: [
      'reverse text',
      'text reverser',
      'flip text',
      'mirror text',
      'backwards text',
      'reverse string',
    ],
    tags: ['reverse', 'flip', 'mirror', 'text'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Reverse Text Online — Flip & Mirror Text Free',
      description:
        'Reverse text online for free. Flip characters or words backward. Mirror text instantly. No sign-up required.',
      keywords: [
        'reverse text online free',
        'text reverser tool',
        'flip text backwards',
        'mirror text generator',
      ],
    },
    relatedToolSlugs: ['case-converter', 'word-counter', 'text-compare', 'remove-whitespace'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'lorem-ipsum',
    slug: 'lorem-ipsum',
    title: 'Lorem Ipsum Generator',
    shortTitle: 'Lorem Ipsum',
    description:
      'Generate Lorem Ipsum placeholder text. Choose the number of paragraphs, sentences, or words. Supports standard Lorem Ipsum and random variation.',
    shortDescription: 'Generate Lorem Ipsum placeholder text.',
    category: 'text',
    subcategory: 'generation',
    icon: FileText,
    keywords: [
      'lorem ipsum generator',
      'placeholder text',
      'dummy text generator',
      'lorem ipsum online',
      'generate lorem ipsum',
      'filler text',
    ],
    tags: ['lorem ipsum', 'placeholder', 'dummy text', 'generate'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Lorem Ipsum Generator — Generate Placeholder Text Free',
      description:
        'Generate Lorem Ipsum placeholder text online. Choose paragraphs, sentences, or word count. Free, instant, no sign-up required.',
      keywords: [
        'lorem ipsum generator free',
        'placeholder text generator',
        'dummy text online',
        'lorem ipsum online',
      ],
    },
    relatedToolSlugs: ['word-counter', 'character-counter', 'case-converter', 'remove-duplicate-lines'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'text-to-slug',
    slug: 'text-to-slug',
    title: 'Text to Slug Converter',
    shortTitle: 'Text to Slug',
    description:
      'Convert any text to a URL-friendly slug. Removes special characters, converts spaces to hyphens, and lowercases the result. Perfect for URLs and SEO.',
    shortDescription: 'Convert text to a URL-friendly slug.',
    category: 'text',
    subcategory: 'transformation',
    icon: Hash,
    keywords: [
      'text to slug',
      'slug generator',
      'url slug converter',
      'seo friendly url',
      'permalink generator',
      'slug maker',
    ],
    tags: ['slug', 'url', 'seo', 'convert', 'text'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Text to Slug Converter — Generate URL Slugs Free',
      description:
        'Convert text to URL-friendly slugs online. Remove special characters, replace spaces with hyphens. Perfect for SEO and blog URLs. Free, instant.',
      keywords: [
        'text to slug converter free',
        'slug generator online',
        'url slug maker',
        'seo friendly url generator',
      ],
    },
    relatedToolSlugs: ['case-converter', 'word-counter', 'url-encoder', 'remove-whitespace'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'remove-whitespace',
    slug: 'remove-whitespace',
    title: 'Remove Whitespace',
    shortTitle: 'Remove Whitespace',
    description:
      'Remove extra spaces, tabs, and blank lines from text. Trim leading and trailing spaces, collapse multiple spaces, or strip all whitespace.',
    shortDescription: 'Remove extra spaces, tabs, and blank lines from text.',
    category: 'text',
    subcategory: 'cleaning',
    icon: AlignJustify,
    keywords: [
      'remove whitespace',
      'remove spaces',
      'trim text',
      'delete blank lines',
      'strip whitespace',
      'remove extra spaces',
      'clean text',
    ],
    tags: ['whitespace', 'spaces', 'clean', 'trim', 'text'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Remove Whitespace — Remove Extra Spaces from Text Free',
      description:
        'Remove extra spaces, tabs, and blank lines from text online. Trim whitespace, collapse spaces, and clean up text. Free, instant, no sign-up.',
      keywords: [
        'remove whitespace online free',
        'remove extra spaces text',
        'trim text online',
        'strip whitespace',
        'clean text spaces',
      ],
    },
    relatedToolSlugs: ['remove-duplicate-lines', 'text-compare', 'word-counter', 'case-converter'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'text-sorter',
    slug: 'text-sorter',
    title: 'Text Sorter',
    shortTitle: 'Sort Text',
    description:
      'Sort lines of text alphabetically, numerically, or by length. Sort ascending or descending. Option to reverse, shuffle, and remove duplicates.',
    shortDescription: 'Sort lines of text alphabetically or numerically.',
    category: 'text',
    subcategory: 'transformation',
    icon: ArrowUpDown,
    keywords: [
      'text sorter',
      'sort lines',
      'alphabetical sort',
      'sort text online',
      'line sorter',
      'arrange text',
    ],
    tags: ['sort', 'arrange', 'alphabetical', 'lines', 'text'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Text Sorter — Sort Lines Alphabetically Online Free',
      description:
        'Sort lines of text alphabetically, numerically, or by length online. Ascending and descending order. Remove duplicates while sorting. Free, instant.',
      keywords: [
        'text sorter online free',
        'sort lines alphabetically',
        'line sorter online',
        'arrange text online',
      ],
    },
    relatedToolSlugs: ['remove-duplicate-lines', 'text-compare', 'remove-whitespace', 'word-counter'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  {
    id: 'find-and-replace',
    slug: 'find-and-replace',
    title: 'Find and Replace Text',
    shortTitle: 'Find & Replace',
    description:
      'Find and replace text with support for plain text and regular expressions. Replace all occurrences or one at a time. Case-sensitive option included.',
    shortDescription: 'Find and replace text with regex support.',
    category: 'text',
    subcategory: 'transformation',
    icon: Replace,
    keywords: [
      'find and replace text',
      'text find replace',
      'bulk text replace',
      'regex find replace',
      'search replace online',
    ],
    tags: ['find', 'replace', 'search', 'regex', 'text'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Find and Replace Text Online — Free Text Replace Tool',
      description:
        'Find and replace text online. Supports regex, case-sensitive mode. Replace all at once or one by one. Free, instant, no sign-up.',
      keywords: [
        'find and replace text online free',
        'bulk text replacer',
        'search replace text',
        'regex find replace online',
      ],
    },
    relatedToolSlugs: ['remove-whitespace', 'text-compare', 'word-counter', 'regex-tester'],
    createdAt: '2025-09-01',
    updatedAt: '2026-06-28',
  },
  /* ── Sprint 7: New Text Tools ─────────────────────────────────────────── */
  {
    id: 'morse-code-converter',
    slug: 'morse-code-converter',
    title: 'Morse Code Converter',
    shortTitle: 'Morse Code',
    description:
      'Convert text to Morse code or decode Morse code back to text. Auto-detects the input direction. Supports all letters, digits, and common punctuation.',
    shortDescription: 'Convert text to Morse code or decode Morse back to text.',
    category: 'text',
    subcategory: 'conversion',
    icon: Radio,
    keywords: ['morse code converter', 'text to morse', 'morse code decoder', 'morse code translator', 'morse code online'],
    tags: ['morse', 'code', 'convert', 'decode', 'text'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Morse Code Converter — Text to Morse & Decode Online Free',
      description: 'Convert text to Morse code or decode Morse code to text online. Auto-detects direction. Free, instant, no sign-up.',
      keywords: ['morse code converter free', 'text to morse code', 'morse code decoder online', 'morse code translator'],
    },
    relatedToolSlugs: ['binary-converter', 'nato-alphabet', 'case-converter', 'text-reverser'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'binary-converter',
    slug: 'binary-converter',
    title: 'Binary Code Converter',
    shortTitle: 'Binary Converter',
    description:
      'Convert text to binary code or decode binary back to readable text. Auto-detects the input. Each character is represented as an 8-bit binary number.',
    shortDescription: 'Convert text to binary or decode binary to text.',
    category: 'text',
    subcategory: 'conversion',
    icon: Binary,
    keywords: ['binary converter', 'text to binary', 'binary to text', 'binary code converter', 'binary decoder', 'binary encoder'],
    tags: ['binary', 'code', 'convert', 'decode', 'text'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Binary Code Converter — Text to Binary & Decode Online Free',
      description: 'Convert text to binary or decode binary to text online. Auto-detects direction. Free, instant, runs in your browser.',
      keywords: ['binary converter online free', 'text to binary converter', 'binary decoder', 'binary to text online'],
    },
    relatedToolSlugs: ['morse-code-converter', 'number-base-converter', 'hash-generator', 'base64-encoder'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'nato-alphabet',
    slug: 'nato-alphabet',
    title: 'NATO Phonetic Alphabet',
    shortTitle: 'NATO Alphabet',
    description:
      'Convert any text to the NATO phonetic alphabet. Spell out words using Alpha, Bravo, Charlie, Delta and more. Perfect for clear communication over radio or phone.',
    shortDescription: 'Convert text to NATO phonetic alphabet (Alpha, Bravo, Charlie...).',
    category: 'text',
    subcategory: 'conversion',
    icon: SquareAsterisk,
    keywords: ['nato phonetic alphabet', 'phonetic alphabet converter', 'nato alphabet', 'spell phonetically', 'alpha bravo charlie'],
    tags: ['nato', 'phonetic', 'alphabet', 'convert', 'text'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'NATO Phonetic Alphabet Converter — Alpha Bravo Charlie Online',
      description: 'Convert text to NATO phonetic alphabet online. Spell out words as Alpha, Bravo, Charlie. Free, instant, no sign-up.',
      keywords: ['nato phonetic alphabet online', 'phonetic alphabet converter free', 'nato alphabet converter', 'spell phonetically online'],
    },
    relatedToolSlugs: ['morse-code-converter', 'binary-converter', 'case-converter', 'text-reverser'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'text-statistics',
    slug: 'text-statistics',
    title: 'Text Statistics',
    shortTitle: 'Text Stats',
    description:
      'Get detailed statistics about any text: word count, unique words, average word length, longest and shortest words, sentence count, reading time, vowels, consonants, and more.',
    shortDescription: 'Detailed text analysis: unique words, avg length, reading time, and more.',
    category: 'text',
    subcategory: 'analysis',
    icon: Activity,
    keywords: ['text statistics', 'text analysis', 'word frequency', 'unique words counter', 'text analyzer', 'average word length'],
    tags: ['statistics', 'analysis', 'text', 'words', 'count'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Text Statistics — Analyze Text Online Free',
      description: 'Get detailed text statistics: unique words, average word length, sentence count, reading time, and more. Free, instant.',
      keywords: ['text statistics online free', 'text analyzer', 'word frequency counter', 'text analysis tool'],
    },
    relatedToolSlugs: ['word-counter', 'character-counter', 'readability-checker', 'keyword-density'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'html-to-text',
    slug: 'html-to-text',
    title: 'HTML to Text Converter',
    shortTitle: 'HTML to Text',
    description:
      'Strip HTML tags and convert HTML content to plain text. Decodes HTML entities (&amp;, &lt;, &gt;, etc.) and preserves readable line breaks.',
    shortDescription: 'Strip HTML tags and extract plain text from HTML.',
    category: 'text',
    subcategory: 'conversion',
    icon: FileText,
    keywords: ['html to text', 'strip html tags', 'html to plain text', 'remove html tags', 'html stripper', 'html text extractor'],
    tags: ['html', 'text', 'strip', 'convert', 'clean'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'HTML to Text Converter — Strip HTML Tags Online Free',
      description: 'Convert HTML to plain text online. Strip all HTML tags, decode HTML entities. Free, instant, runs in your browser.',
      keywords: ['html to text converter free', 'strip html tags online', 'remove html tags', 'html to plain text'],
    },
    relatedToolSlugs: ['html-formatter', 'html-encoder', 'markdown-preview', 'word-counter'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'palindrome-checker',
    slug: 'palindrome-checker',
    title: 'Palindrome Checker',
    shortTitle: 'Palindrome Checker',
    description:
      'Check if a word or phrase is a palindrome (reads the same forwards and backwards). Ignores spaces, punctuation, and case. Also finds the longest palindromic word.',
    shortDescription: 'Check if text is a palindrome (reads same forwards and backwards).',
    category: 'text',
    subcategory: 'analysis',
    icon: Shield,
    keywords: ['palindrome checker', 'is it a palindrome', 'palindrome detector', 'palindrome words', 'palindrome phrase'],
    tags: ['palindrome', 'check', 'text', 'analysis', 'words'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Palindrome Checker — Check if Text is a Palindrome Free',
      description: 'Check if a word or phrase is a palindrome online. Ignores spaces and punctuation. Finds longest palindromic word. Free, instant.',
      keywords: ['palindrome checker online free', 'palindrome detector', 'check palindrome online', 'is it a palindrome'],
    },
    relatedToolSlugs: ['word-counter', 'text-reverser', 'case-converter', 'text-statistics'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
  {
    id: 'roman-numeral-converter',
    slug: 'roman-numeral-converter',
    title: 'Roman Numeral Converter',
    shortTitle: 'Roman Numerals',
    description:
      'Convert numbers to Roman numerals or decode Roman numerals to numbers. Auto-detects the input direction. Supports values from 1 to 3999 (I to MMMCMXCIX).',
    shortDescription: 'Convert numbers to Roman numerals and vice versa.',
    category: 'text',
    subcategory: 'conversion',
    icon: Hash,
    keywords: ['roman numeral converter', 'roman numerals', 'number to roman numeral', 'roman numeral translator', 'roman numeral decoder', 'arabic to roman'],
    tags: ['roman numerals', 'convert', 'number', 'text'],
    difficulty: 'beginner',
    status: 'active',
    processingMode: 'browser',
    seo: {
      title: 'Roman Numeral Converter — Convert Numbers to Roman Free',
      description: 'Convert numbers to Roman numerals or decode Roman numerals to numbers online. Auto-detects direction. Free, instant, no sign-up.',
      keywords: ['roman numeral converter online free', 'number to roman numeral', 'roman numeral decoder', 'roman numeral translator'],
    },
    relatedToolSlugs: ['binary-converter', 'number-base-converter', 'morse-code-converter', 'case-converter'],
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
  },
]

